Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2019-04, with the labels that each got.

#130 adding pause and play button
  scss/_carousel.scss
  scss/_o-carousel.scss
  site/_includes/scripts.html
  site/docs/4.3/components/carousel.md
  site/docs/4.3/components/custom-carousel.md
Labels: v4

#137 Update oswitch
  js/src/button.js
  scss/_o-switches.scss
  site/_includes/boostwatch/forms.html
  site/_includes/boostwatch/switches.html
  site/_includes/boostwatch/tables.html
  site/docs/4.3/assets/scss/_boosted-docs.scss
  site/docs/4.3/components/buttons.md
  site/docs/4.3/components/forms.md
  site/docs/4.3/examples/administration-edition-page/index.html
  site/docs/4.3/examples/administration-mainpage/edit.html
  site/docs/4.3/examples/checkout/index.html
  site/docs/4.3/examples/dashboard-orange-branded/index.html
  site/docs/4.3/examples/floating-labels/index.html
  site/docs/4.3/examples/sign-in/index.html
Labels: v4

#148 fic(custom-switch): fix custom-switch focus fixes issue #146
  scss/_custom-forms.scss
Labels: bug, v4

#147 Fix examples template
  scss/_o-carousel.scss
  site/docs/4.3/components/carousel.md
  site/docs/4.3/components/custom-carousel.md
  site/docs/4.3/examples/orange-homepage/index.html
  site/docs/4.3/examples/orange-homepage/sample.css
Labels: bug, enhancement

#151 fix(examples): replace jquery.js by jquery.slim in script inclusion
  site/docs/4.3/examples/administration-edition-page/index.html
  site/docs/4.3/examples/administration-mainpage/edit.html
  site/docs/4.3/examples/administration-mainpage/index.html
  site/docs/4.3/examples/content-panel/index.html
  site/docs/4.3/examples/dashboard-orange-branded/index.html
  site/docs/4.3/examples/demo/index.html
  site/docs/4.3/examples/news-template/index.html
  site/docs/4.3/examples/orange-form/index.html
  site/docs/4.3/examples/orange-grid/index-fluid.html
  site/docs/4.3/examples/orange-grid/index.html
  site/docs/4.3/examples/orange-homepage/index.html
  site/docs/4.3/examples/product-details/index.html
  site/docs/4.3/examples/quick-links/index.html
Labels: v4
