Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2020-03, with the labels that each got.

#332 Carousels
  package-lock.json
  scss/_carousel.scss
  scss/_o-carousel.scss
  scss/_variables.scss
  site/_includes/scripts.html
  site/docs/4.4/assets/css/docs.min.css
  site/docs/4.4/assets/css/docs.min.css.map
  site/docs/4.4/components/carousel.md
  site/docs/4.4/components/custom-carousel.md
Labels: brand, bug, component, documentation, v4

#337 [o-tabs] — arrow icons size & position
  scss/_o-tabs.scss
Labels: bug, v4

#335 Megamenu fixes
  .github/workflows/test.yml
  bundlesize.config.json
  js/src/o-megamenu.js
  js/tests/index.html
  js/tests/karma.conf.js
  package-lock.json
  package.json
  scss/_o-megamenu.scss
  site/docs/4.4/components/orange-megamenu.md
  site/docs/4.4/examples/news-template/index.html
Labels: bug, component, javascript, v4

#338 Merge/v4 dev@8b6dd449d
  .github/workflows/test.yml
  .gitignore
  Gemfile
  Gemfile.lock
  build/build-plugins.js
  build/rollup.config.js
  build/ship.sh
  build/vnu-jar.js
  js/src/button.js
  js/tests/integration/rollup.bundle.js
  js/tests/unit/button.js
  package-lock.json
  package.json
  scss/_buttons.scss
  scss/_dropdown.scss
  scss/_list-group.scss
  scss/_modal.scss
  scss/_nav.scss
  scss/_o-step-bar.scss
  scss/_pagination.scss
  scss/_reboot.scss
  site/docs/4.4/examples/dashboard/dashboard.css
  site/docs/4.4/examples/dashboard/index.html
  site/docs/4.4/getting-started/build-tools.md
Labels: dependencies, documentation, tools, v4

#341 Megamenu defaults
  js/tests/karma.conf.js
  js/tests/unit/o-megamenu.js
  scss/_o-megamenu.scss
Labels: component, javascript, v4

#344 Fix dropdown menu alignment
  scss/_navbar.scss
Labels: bug, v4
