Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2020-11, with the labels that each got.

#541 Ensure small gutters depends on main gutters
  scss/_variables.scss
  scss/mixins/_grid.scss
Labels: bug, v4

#542 chore(merge v4-dev): latest patched commit → 5664e728b
  build/rollup.config.js
  js/index.js
  js/src/index.js
Labels: chore, javascript, merge, v4

#544 docs(grid): duplicate content, missed in last merge
  site/docs/4.5/layout/grid.md
Labels: docs, v4

#546 chore(merge v4-dev): latest patched commit → 44d54eb57
  .eslintignore
  .eslintrc.json
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  js/src/o-priority-nav.js
  js/tests/unit/tooltip.js
  package-lock.json
  package.js
  package.json
  site/docs/4.5/assets/scss/_anchor.scss
Labels: chore, merge, v4

#547 chore(merge main): latest patched commit → f989f8fb3
  .browserslistrc
  build/build-plugins.js
  js/src/dom/event-handler.js
  js/src/dom/polyfill.js
  js/src/dom/selector-engine.js
  js/tests/browsers.js
  js/tests/karma.conf.js
  js/tests/visual/alert.html
  js/tests/visual/button.html
  js/tests/visual/carousel.html
  js/tests/visual/collapse.html
  js/tests/visual/dropdown.html
  js/tests/visual/modal.html
  js/tests/visual/popover.html
  js/tests/visual/scrollspy.html
  js/tests/visual/tab.html
  js/tests/visual/toast.html
  js/tests/visual/tooltip.html
  package-lock.json
  package.json
  scss/_reboot.scss
  scss/forms/_form-control.scss
  scss/forms/_form-range.scss
  scss/forms/_form-select.scss
  site/assets/js/search.js
  site/assets/scss/_component-examples.scss
  site/assets/scss/_subnav.scss
  site/content/docs/5.0/content/typography.md
  site/content/docs/5.0/customize/optimize.md
  site/content/docs/5.0/forms/range.md
  site/content/docs/5.0/getting-started/browsers-devices.md
  site/content/docs/5.0/getting-started/introduction.md
  site/content/docs/5.0/migration.md
  site/content/docs/5.0/utilities/api.md
  site/layouts/_default/examples.html
Labels: chore, merge, v5

#549 chore(merge v4-dev): latest patched commit → 9e9e1e61d
  site/docs/4.5/components/navbar.md
  site/docs/4.5/getting-started/introduction.md
Labels: chore, merge, v4

#554 chore(dependabot): upgrade to version 2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: chore, v4

#568 chore(merge v4-dev): latest patched commit → 4bdaa2604
  .bundlewatch.config.json
  Gemfile.lock
  js/src/carousel.js
  js/tests/unit/carousel.js
  package-lock.json
  package.json
  scss/_carousel.scss
  scss/_custom-forms.scss
  scss/_navbar.scss
  scss/_progress.scss
  scss/_reboot.scss
  scss/_spinners.scss
  scss/_variables.scss
  scss/mixins/_forms.scss
  scss/mixins/_image.scss
  site/_data/browser-features.yml
  site/docs/4.5/assets/js/src/search.js
  site/docs/4.5/components/forms.md
  site/docs/4.5/components/input-group.md
  site/docs/4.5/components/navbar.md
  site/docs/4.5/examples/floating-labels/index.html
  site/docs/4.5/getting-started/browsers-devices.md
  site/docs/4.5/getting-started/download.md
  site/docs/4.5/utilities/interactions.md
Labels: chore, dependencies, merge, v4

#571 fix(alerts): ensure content don't overlap icon
  scss/_alert.scss
Labels: bug, component, v5
