Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2020-09, with the labels that each got.

#467 Add default vertical margins to pagination
  scss/_pagination.scss
  scss/_variables.scss
Labels: component, v4

#468 Add default vertical margins to pagination
  scss/_pagination.scss
  scss/_variables.scss
Labels: component, v5

#465 Drop important to follow up text-emphasis-variant() evolution
  scss/utilities/_text.scss
Labels: accessibility, brand, v4

#466 Use supporting colors for badges
  scss/_badge.scss
Labels: brand, component, v4

#470 Remove white space
  site/docs/4.5/components/orange-footer.md
Labels: bug, docs, v4

#477 Ensure legends are bold
  scss/_reboot.scss
Labels: brand, v4

#479 chore(merge v4-dev); last patched commit → 3be585990
  .eslintignore
  .eslintrc.json
  build/.eslintrc.json
  build/autoshot.js
  build/build-plugins.js
  build/change-version.js
  build/docs-rtl.js
  build/generate-sri.js
  build/postcss.config.js
  build/zip-examples.js
  js/src/alert.js
  js/src/button.js
  js/src/carousel.js
  js/src/collapse.js
  js/src/dropdown.js
  js/src/index.js
  js/src/modal.js
  js/src/o-megamenu.js
  js/src/o-navbar.js
  js/src/o-priority-nav.js
  js/src/o-scroll-up.js
  js/src/o-tab.js
  js/src/popover.js
  js/src/scrollspy.js
  js/src/tab.js
  js/src/toast.js
  js/src/tools/sanitizer.js
  js/src/tooltip.js
  js/src/util.js
  js/tests/browsers.js
  js/tests/karma.conf.js
  js/tests/unit/.eslintrc.json
  js/tests/unit/carousel.js
  js/tests/unit/collapse.js
  js/tests/unit/dropdown.js
  js/tests/unit/modal.js
  js/tests/unit/o-megamenu.js
  js/tests/unit/o-navbar.js
  js/tests/unit/o-scroll-up.js
  js/tests/unit/o-tabs.js
  js/tests/unit/popover.js
  js/tests/unit/scrollspy.js
  js/tests/unit/tab.js
  js/tests/unit/toast.js
  js/tests/unit/tooltip.js
  js/tests/unit/util.js
  package-lock.json
  package.json
  site/.eslintrc.json
  site/docs/4.5/assets/js/src/application-boosted.js
  site/docs/4.5/assets/js/src/application.js
  site/docs/4.5/assets/js/src/ie-emulation-modes-warning.js
  site/docs/4.5/assets/js/src/search.js
  site/docs/4.5/examples/checkout/form-validation.js
  site/docs/4.5/examples/dashboard/dashboard.js
  site/docs/4.5/examples/orange-form/form.js
  site/docs/4.5/getting-started/build-tools.md
Labels: chore, dependencies, merge, v4

#483 docs(tables): revamp classless table styles in docs
  site/docs/4.5/assets/scss/_content.scss
Labels: docs, v4

#484 fix(cards): ensure cards groups' margins stick to spacers map
  scss/_variables.scss
Labels: component, v4

#487 fix(dropdown): ensure to rely on dropdown state to rotate its caret
  scss/_navbar.scss
Labels: bug, v4

#489 chore(merge main): latest patched commit → c0fe383
  .bundlewatch.config.json
  .github/CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  scss/_alert.scss
  scss/_close.scss
  scss/_dropdown.scss
  scss/_helpers.scss
  scss/_modal.scss
  scss/_navbar.scss
  scss/_toasts.scss
  scss/_utilities.scss
  scss/_variables.scss
  scss/forms/_input-group.scss
  scss/helpers/_embed.scss
  scss/helpers/_ratio.scss
  scss/mixins/_container.scss
  scss/mixins/_visually-hidden.scss
  site/assets/scss/_boosted.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.0/components/alerts.md
  site/content/docs/5.0/components/close-button.md
  site/content/docs/5.0/components/modal.md
  site/content/docs/5.0/components/toasts.md
  site/content/docs/5.0/getting-started/accessibility.md
  site/content/docs/5.0/getting-started/webpack.md
  site/content/docs/5.0/guidelines/logos.md
  site/content/docs/5.0/helpers/embed.md
  site/content/docs/5.0/helpers/ratio.md
  site/content/docs/5.0/migration.md
  site/content/docs/5.0/utilities/position.md
  site/data/sidebar.yml
  site/layouts/_default/docs.html
  site/layouts/shortcodes/alert.html
Labels: chore, merge, v5

#492 Update Orange popin example
  site/docs/4.5/components/modal.md
Labels: docs, v4

#494 Drop v4-dev merge notifications on Mattermost
  .github/workflows/notify.yml
Labels: chore, v4

#496 style(variables): small adjustments to match our conventions
  scss/_variables.scss
Labels: chore, v4

#497 Smaller margin between stepbar items
  scss/_o-step-bar.scss
  scss/_variables.scss
Labels: brand, bug, v4

#498 chore(merge v4-dev): last patched commit → e45fbe7
  site/docs/4.5/components/popovers.md
Labels: chore, merge, v4

#499 chore(merge main): latest patched commit → caef121
  .bundlewatch.config.json
  README.md
  js/src/tooltip.js
  js/tests/unit/tooltip.spec.js
  scss/_carousel.scss
  scss/_dropdown.scss
  scss/_variables.scss
  site/content/docs/5.0/components/carousel.md
  site/content/docs/5.0/components/dropdowns.md
  site/layouts/partials/callout-danger-async-methods.md
Labels: chore, merge, v5

#502 chore(merge main): latest patched commit → 331566bc8
  package-lock.json
  package.json
  scss/_navbar.scss
  scss/_utilities.scss
  scss/_variables.scss
  site/assets/scss/_boosted.scss
  site/assets/scss/_masthead.scss
  site/assets/scss/_sidebar.scss
  site/assets/scss/_subnav.scss
  site/assets/scss/_toc.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.0/migration.md
  site/content/docs/versions.md
  site/layouts/_default/docs.html
  site/layouts/_default/guidelines.html
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/docs-sidebar.html
  site/layouts/partials/docs-subnav.html
  site/layouts/partials/docs-versions.html
  site/layouts/partials/guidelines-sidebar.html
  site/layouts/partials/guidelines-subnav.html
  site/layouts/partials/icons/collapse.svg
  site/layouts/partials/icons/expand.svg
  site/layouts/partials/icons/list.svg
  site/static/docs/5.0/assets/img/homepage-hero.svg
Labels: chore, merge, v5

#503 chore(merge main): latest patched commit → ec812dcf8
  .stylelintrc
  package-lock.json
  package.json
  scss/_card.scss
  scss/_functions.scss
  scss/_nav.scss
  scss/_reboot.scss
  scss/_spinners.scss
  scss/_variables.scss
  scss/forms/_form-check.scss
  scss/mixins/_border-radius.scss
  scss/mixins/_container.scss
  scss/mixins/_grid.scss
  scss/mixins/_transition.scss
  site/assets/scss/_sidebar.scss
  site/content/docs/5.0/components/alerts.md
Labels: chore, merge, v5

#504 chore(merge v4-dev): latest patched commit → f927a95b6
  site/docs/4.5/getting-started/download.md
  site/docs/4.5/getting-started/introduction.md
  site/docs/4.5/getting-started/rtl.md
Labels: chore, merge, v4

#506 docs(forms): fix auto-sizing example alignment
  site/docs/4.5/components/forms.md
Labels: docs, v4
