Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2020-06, with the labels that each got.

#406 chore(merge v4-dev): last patched commit → f4a7888
  scss/_custom-forms.scss
  scss/mixins/_forms.scss
  site/docs/4.5/components/card.md
  site/docs/4.5/content/images.md
  site/docs/4.5/extend/icons.md
  site/docs/4.5/getting-started/download.md
Labels: chore, merge, v4

#407 Ensure img in carousels are 100% wide
  scss/_carousel.scss
Labels: bug, v4

#408 Ensure focus-visible is used on toggle buttons
  js/src/button.js
Labels: bug, component, js, v4

#409 chore(merge v4-dev): last patched commit → 3caea1ca0
  .bundlewatch.config.json
  .eslintrc.json
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  build/babel-helpers.js
  build/build-plugins.js
  build/rollup.config.js
  js/src/modal.js
  js/tests/integration/rollup.bundle.js
  js/tests/unit/modal.js
  js/tests/visual/modal.html
  package-lock.json
  package.json
  scss/_card.scss
  scss/_reboot.scss
  scss/utilities/_text.scss
  site/docs/4.5/components/card.md
  site/docs/4.5/components/modal.md
  site/docs/4.5/utilities/text.md
Labels: chore, merge, v4

#411 Use only padding to handle dropdown height
  scss/_dropdown.scss
  scss/_navbar.scss
  scss/_variables.scss
Labels: bug, v4

#419 fix(docs): some English typos
  NOTICE.txt
  scss/orangeHelvetica.scss
  scss/orangeIcons.scss
  site/docs/4.5/assets/js/vendor/tarteaucitron.services.js
  site/docs/4.5/getting-started/introduction.md
  site/docs/4.5/getting-started/rtl.md
Labels: brand, chore, v4

#422 chore(README): fix logo
  README.md
Labels: brand, chore, v5

#423 chore(README): update quick start and badges
  README.md
Labels: chore, v5

#424 Fix examples zip name and assets
  build/zip-examples.js
Labels: bug, chore, v4

#425 fix some broken links
  _config.yml
  site/_includes/footer.html
  site/docs/4.5/about/boosted-license.md
Labels: chore, docs, v4

#426 .btn-icon sizes
  scss/_buttons.scss
  scss/_variables.scss
  site/docs/4.5/components/buttons.md
Labels: brand, bug, v4

#428 Licence wording and update NOTICE.txt
  NOTICE.txt
  scss/orangeHelvetica.scss
  site/docs/4.5/getting-started/introduction.md
  site/docs/4.5/getting-started/rtl.md
Labels: chore, v4

#427 Increase spacings to ease list-group alignment
  scss/_variables.scss
Labels: bug, v4

#430 chore(merge v4-dev): last patched commit → 4f44a2afd
  js/src/button.js
  js/tests/unit/button.js
  scss/_custom-forms.scss
  scss/_grid.scss
  scss/_toasts.scss
  scss/_variables.scss
  scss/mixins/_grid-framework.scss
  site/docs/4.5/components/toasts.md
  site/docs/4.5/examples/floating-labels/floating-labels.css
  site/docs/4.5/examples/floating-labels/index.html
Labels: merge, v4

#435 chore(backport v4-dev): #301 #427 #428
  NOTICE.txt
  scss/_pagination.scss
  scss/_variables.scss
  scss/orange-helvetica.scss
  site/content/docs/5.0/getting-started/introduction.md
Labels: chore, v5
