Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2021-12, with the labels that each got.

#795 Supra Bars (Standard, With Langs, With Actions)
  .bundlewatch.config.json
  .cspell.json
  scss/_orange-navbar.scss
  scss/_variables.scss
  scss/boosted.scss
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/components/orange-navbar.md
  site/content/docs/5.1/guidelines/global-headers.md
  site/content/docs/5.1/migration.md
  site/data/sidebar.yml
  site/layouts/shortcodes/orange-supra.html
  site/static/docs/5.1/assets/img/boosted-sprite.svg
  site/static/docs/5.1/assets/img/navbar-contact.png
Labels: v5, brand, component, back-from-v4

#958 Chore/merge main@2fe90d8
  .bundlewatch.config.json
  config.yml
  js/tests/README.md
  js/tests/browsers.js
  js/tests/karma.conf.js
  js/tests/unit/alert.spec.js
  js/tests/unit/base-component.spec.js
  js/tests/unit/button.spec.js
  js/tests/unit/carousel.spec.js
  js/tests/unit/collapse.spec.js
  js/tests/unit/dom/data.spec.js
  js/tests/unit/dom/event-handler.spec.js
  js/tests/unit/dom/manipulator.spec.js
  js/tests/unit/dom/selector-engine.spec.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/jquery.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/offcanvas.spec.js
  js/tests/unit/popover.spec.js
  js/tests/unit/scrollspy.spec.js
  js/tests/unit/tab.spec.js
  js/tests/unit/toast.spec.js
  js/tests/unit/tooltip.spec.js
  js/tests/unit/util/backdrop.spec.js
  js/tests/unit/util/component-functions.spec.js
  js/tests/unit/util/focustrap.spec.js
  js/tests/unit/util/index.spec.js
  js/tests/unit/util/scrollbar.spec.js
  js/tests/unit/util/swipe.spec.js
  js/tests/unit/util/template-factory.spec.js
  package-lock.json
  package.json
  site/content/docs/5.1/layout/gutters.md
Labels: v5, merge

#959 Chore/merge main@385fea4
  build/svgo.yml
  js/src/dropdown.js
  js/src/popover.js
  js/src/tooltip.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/popover.spec.js
  js/tests/unit/tooltip.spec.js
  site/content/docs/5.1/migration.md
Labels: v5, merge

#966 Create supra bars shortcodes and reintroduce navbar example
  site/content/docs/5.1/components/badge.md
  site/content/docs/5.1/components/orange-navbar.md
  site/content/docs/5.1/examples/navbars/index.html
  site/content/docs/5.1/examples/navbars/navbar.css
  site/content/docs/5.1/guidelines/global-headers.md
  site/data/examples.yml
  site/layouts/shortcodes/orange-supra.html
  site/static/docs/5.1/assets/img/examples/navbars.png
  site/static/docs/5.1/assets/img/examples/navbars@2x.png
Labels: v5, examples

#965 Some drops on guidelines
  site/content/docs/5.1/components/alerts.md
  site/content/docs/5.1/components/card.md
  site/content/docs/5.1/components/close-button.md
  site/content/docs/5.1/components/navs-tabs.md
  site/content/docs/5.1/components/tooltips.md
  site/content/docs/5.1/content/tables.md
  site/content/docs/5.1/content/typography.md
  site/content/docs/5.1/forms/range.md
  site/content/docs/5.1/forms/select.md
  site/content/docs/5.1/guidelines/_index.md
  site/content/docs/5.1/guidelines/alerts.md
  site/content/docs/5.1/guidelines/buttons.md
  site/content/docs/5.1/guidelines/cards.md
  site/content/docs/5.1/guidelines/data-tables.md
  site/content/docs/5.1/guidelines/footers.md
  site/content/docs/5.1/guidelines/forms.md
  site/content/docs/5.1/guidelines/global-headers.md
  site/content/docs/5.1/guidelines/global-menu.md
  site/content/docs/5.1/guidelines/global-search.md
  site/content/docs/5.1/guidelines/local-headers.md
  site/content/docs/5.1/guidelines/modals.md
  site/content/docs/5.1/guidelines/navigation.md
  site/content/docs/5.1/guidelines/progress-indicators.md
  site/content/docs/5.1/guidelines/responsive-grid.md
  site/content/docs/5.1/guidelines/stickers.md
  site/content/docs/5.1/helpers/colored-links.md
  site/content/docs/5.1/layout/grid.md
  site/data/guidelines.yml
  site/layouts/_default/guidelines.html
  site/layouts/shortcodes/alert.html
  site/static/docs/5.1/assets/img/boosted-sprite.svg
  site/static/docs/5.1/assets/img/platforms/android.png
  site/static/docs/5.1/assets/img/platforms/conversational.png
  site/static/docs/5.1/assets/img/platforms/extended-reality.png
  site/static/docs/5.1/assets/img/platforms/iOS.png
Labels: v5

#861 No border for focused <select> in Forms > Custom styles
  scss/_variables.scss
Labels: v5, fix, css

#923 Fix (scrollspy): Replace navbar and nested nav examples
  site/assets/scss/_alerts.scss
  site/assets/scss/docs.scss
  site/content/docs/5.1/components/scrollspy.md
  site/layouts/shortcodes/ods-incompatibility-alert.html
Labels: v5, fix

#967 Chore/merge main@2a7015e
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/optimize.yml
  .github/workflows/pa11y.yml
  .github/workflows/percy.yml
  README.md
  js/src/tooltip.js
  js/tests/unit/carousel.spec.js
  js/tests/unit/collapse.spec.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/offcanvas.spec.js
  js/tests/unit/tab.spec.js
  js/tests/unit/tooltip.spec.js
  package-lock.json
  package.json
  scss/_variables.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_layout.scss
  site/assets/scss/_navbar.scss
  site/assets/scss/_sidebar.scss
  site/assets/scss/_subnav.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.1/examples/dropdowns/index.html
  site/content/docs/5.1/forms/overview.md
  site/layouts/partials/docs-navbar.html
Labels: v5, merge

#969 Chore/merge main@886b940
  .github/workflows/js.yml
  js/src/base-component.js
  js/src/carousel.js
  js/src/collapse.js
  js/src/dropdown.js
  js/src/modal.js
  js/src/offcanvas.js
  js/src/popover.js
  js/src/scrollspy.js
  js/src/tab.js
  js/src/toast.js
  js/src/tooltip.js
  js/src/util/backdrop.js
  js/src/util/config.js
  js/src/util/focustrap.js
  js/src/util/index.js
  js/src/util/scrollbar.js
  js/src/util/swipe.js
  js/src/util/template-factory.js
  js/tests/unit/dom/event-handler.spec.js
  js/tests/unit/dom/selector-engine.spec.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/tooltip.spec.js
  js/tests/unit/util/config.spec.js
  js/tests/unit/util/index.spec.js
  js/tests/unit/util/scrollbar.spec.js
Labels: v5, merge

#960 feat(guidelines): drop design guidelines content and replace it with a simpler page
  .github/workflows/percy.yml
  config.yml
  site/assets/scss/_boosted.scss
  site/content/docs/5.1/about/brand.md
  site/content/docs/5.1/components/alerts.md
  site/content/docs/5.1/components/close-button.md
  site/content/docs/5.1/components/navs-tabs.md
  site/content/docs/5.1/components/tooltips.md
  site/content/docs/5.1/content/tables.md
  site/content/docs/5.1/content/typography.md
  site/content/docs/5.1/customize/color.md
  site/content/docs/5.1/examples/cards/index.html
  site/content/docs/5.1/guidelines/_index.md
  site/content/docs/5.1/guidelines/alerts.md
  site/content/docs/5.1/guidelines/buttons.md
  site/content/docs/5.1/guidelines/cards.md
  site/content/docs/5.1/guidelines/colors.md
  site/content/docs/5.1/guidelines/data-tables.md
  site/content/docs/5.1/guidelines/footers.md
  site/content/docs/5.1/guidelines/forms.md
  site/content/docs/5.1/guidelines/global-headers.md
  site/content/docs/5.1/guidelines/global-menu.md
  site/content/docs/5.1/guidelines/global-search.md
  site/content/docs/5.1/guidelines/line-styles.md
  site/content/docs/5.1/guidelines/local-headers.md
  site/content/docs/5.1/guidelines/logos.md
  site/content/docs/5.1/guidelines/modals.md
  site/content/docs/5.1/guidelines/navigation.md
  site/content/docs/5.1/guidelines/progress-indicators.md
  site/content/docs/5.1/guidelines/responsive-grid.md
  site/content/docs/5.1/guidelines/stickers.md
  site/content/docs/5.1/guidelines/typography.md
  site/content/docs/5.1/utilities/background.md
  site/content/docs/5.1/utilities/borders.md
  site/data/design-guidelines.yml
  site/data/examples.yml
  site/data/guidelines.yml
  site/layouts/_default/guidelines.html
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/home/masthead-followup.html
  site/layouts/shortcodes/alert.html
  site/static/docs/5.1/assets/img/boosted-sprite.svg
  site/static/docs/5.1/assets/img/examples/cards.png
  site/static/docs/5.1/assets/img/examples/cards@2x.png
  site/static/docs/5.1/assets/img/platforms/android.png
  site/static/docs/5.1/assets/img/platforms/conversational.png
  site/static/docs/5.1/assets/img/platforms/extended-reality.png
  site/static/docs/5.1/assets/img/platforms/iOS.png
Labels: v5, feature

#981 Chore/merge main@28f7c94
  .stylelintrc
  package-lock.json
  package.json
  scss/_modal.scss
  scss/_nav.scss
  scss/_reboot.scss
  scss/_stepped-process.scss
  scss/_utilities.scss
  scss/forms/_form-select.scss
  scss/mixins/_reset-text.scss
  scss/mixins/_utilities.scss
  scss/orange-helvetica.scss
  site/assets/scss/_algolia.scss
  site/assets/scss/_layout.scss
  site/assets/scss/_placeholder-img.scss
  site/assets/scss/_syntax.scss
  site/content/docs/5.1/examples/.stylelintrc
  site/content/docs/5.1/examples/cheatsheet/cheatsheet.css
  site/content/docs/5.1/examples/cheatsheet/cheatsheet.rtl.css
  site/content/docs/5.1/examples/features/features.css
  site/content/docs/5.1/utilities/flex.md
Labels: v5, merge

#984 Reintroduce Bootstrap Community section in introduction
  config.yml
  site/content/docs/5.1/getting-started/introduction.md
Labels: v5, docs

#985 Fix broken links in 'Unused CSS' section
  site/content/docs/5.1/customize/optimize.md
Labels: v5, docs, fix

#986 Docs: Replace Bootstrap reference with Boosted in Offcanvas example
  site/content/docs/5.1/components/offcanvas.md
Labels: v5, docs, fix

#673 fix focus-visible import
  .bundlewatch.config.json
  js/index.js
  package-lock.json
  package.json
Labels: v4, fix

#989 chore/merge-main@4216254
  .bundlewatch.config.json
  build/postcss.config.js
  js/src/modal.js
  js/src/popover.js
  js/src/scrollspy.js
  js/src/tooltip.js
  js/tests/unit/popover.spec.js
  scss/_alert.scss
  scss/_button-group.scss
  scss/_variables.scss
  scss/helpers/_position.scss
  scss/mixins/_alert.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.1/components/alerts.md
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/content/reboot.md
  site/content/docs/5.1/examples/cheatsheet-rtl/index.html
  site/content/docs/5.1/examples/cheatsheet/index.html
  site/content/docs/5.1/getting-started/contents.md
  site/content/docs/5.1/helpers/position.md
  site/layouts/shortcodes/orange-supra.html
Labels: v5, merge

#997 Chore/merge main@0d4213b
  config.yml
  js/src/carousel.js
  js/src/tooltip.js
  js/tests/unit/carousel.spec.js
  package-lock.json
  package.json
  site/content/docs/5.1/components/alerts.md
  site/content/docs/5.1/helpers/position.md
Labels: v5, merge

#998 Chore/merge v4 dev@9c60983
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/dart-sass.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .stylelintrc
  README.md
  build/change-version.js
  build/svgo.yml
  js/index.js
  package-lock.json
  package.json
  scss/_navbar.scss
  scss/_reboot.scss
  scss/mixins/_reset-text.scss
  scss/orangeHelvetica.scss
  scss/orangeIcons.scss
  site/assets/js/application-boosted.js
  site/assets/scss/_algolia.scss
  site/assets/scss/_boosted-docs.scss
  site/assets/scss/_placeholder-img.scss
  site/assets/scss/_syntax.scss
  site/content/docs/4.6/components/toasts.md
  site/content/docs/4.6/essentials/.stylelintrc
  site/content/docs/4.6/examples/.stylelintrc
  site/content/docs/4.6/getting-started/accessibility.md
  site/content/docs/4.6/getting-started/contents.md
  site/content/docs/4.6/utilities/flex.md
  site/layouts/partials/nav-boostwatch.html
  site/static/docs/4.6/assets/css/tarteaucitronboosted.css
Labels: v4, merge

#1002 Chore/merge main@deb8e3f
  .cspell.json
  site/content/docs/5.1/components/carousel.md
  site/content/docs/5.1/components/navs-tabs.md
Labels: v5, merge

#1003 chore(merge main): patched commit ⭢ 33c7f9f
  package-lock.json
  package.json
Labels: v5, merge

#1006 chore(merge main): patched commit ⭢ 2c9ecd0
  site/content/docs/5.1/utilities/api.md
Labels: v5, merge

#1004 feat(githubWorkflows): Adding Percy and Browserstack jobs
  .github/workflows/browserstack.yml
  .github/workflows/percy.yml
Labels: v5, github_actions, enhancement
