Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2021-09, with the labels that each got.

#789 docs(version): automatically retrieve latest version in version selector
  site/layouts/partials/docs-versions.html
Labels: v5, fix

#792 Rename "v5-dev" to "main"
  .bundlewatch.config.json
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/pa11y.yml
  .github/workflows/percy.yml
  README.md
  build/banner.js
  js/dist/dom/polyfill.js
  js/dist/dom/polyfill.js.map
  scss/boosted-grid.scss
  scss/boosted-reboot.scss
  scss/boosted-utilities.scss
  scss/boosted.scss
  site/layouts/_default/docs.html
  site/layouts/partials/footer.html
Labels: v5, enhancement

#796 fix(doc): update broken links in README.md
  README.md
Labels: v5, docs

#808 Fix orange navbar 1px border bottom color
  scss/_o-navbar.scss
Labels: v4, fix

#806 chore(release): resync nuget/*.nuspec files with Bootstrap
  nuget/boosted.nuspec
  nuget/boosted.sass.nuspec
Labels: v5, chore, backport-to-v4

#807 Chore/merge main@bdfb4cc
  build/.pa11yci.json
  config.yml
  js/src/carousel.js
  js/src/collapse.js
  js/src/offcanvas.js
  js/src/util/backdrop.js
  js/src/util/focustrap.js
  js/src/util/sanitizer.js
  js/tests/helpers/fixture.js
  js/tests/unit/carousel.spec.js
  js/tests/unit/collapse.spec.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/offcanvas.spec.js
  package-lock.json
  package.json
  scss/_button-group.scss
  scss/_buttons.scss
  scss/_tables.scss
  scss/_variables.scss
  scss/forms/_form-select.scss
  scss/mixins/_visually-hidden.scss
  site/assets/js/application.js
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/components/list-group.md
  site/content/docs/5.1/components/modal.md
  site/content/docs/5.1/components/offcanvas.md
  site/content/docs/5.1/components/placeholders.md
  site/content/docs/5.1/content/images.md
  site/content/docs/5.1/content/reboot.md
  site/content/docs/5.1/customize/optimize.md
  site/content/docs/5.1/customize/sass.md
  site/content/docs/5.1/examples/cheatsheet/index.html
  site/content/docs/5.1/forms/checks-radios.md
  site/content/docs/5.1/getting-started/rfs.md
  site/content/docs/5.1/helpers/text-truncation.md
Labels: v5, chore, merge

#813 chore(release): resync nuget/*.nuspec files with Bootstrap
  nuget/boosted.4.0.0-beta3.nupkg
  nuget/boosted.nuspec
  nuget/boosted.sass.4.0.0-beta3.nupkg
  nuget/boosted.sass.nuspec
Labels: v4, backport-to-v4, fix

#817 chore(merge main): patched commit -> 60d3eb3
  package-lock.json
  package.json
Labels: v5, merge

#809 fix(ci): 'if' is defined two times in JS GitHub CI workflow
  .github/workflows/js.yml
Labels: v4, fix

#819 chore(deps): regenerate package-lock.json
  package-lock.json
Labels: v5, dependencies, chore

#826 Chore/merge main@4ffdef3
  .bundlewatch.config.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  config.yml
  js/src/util/sanitizer.js
  package-lock.json
  package.json
  scss/_variables.scss
  site/content/docs/5.1/components/modal.md
  site/content/docs/5.1/examples/cheatsheet-rtl/index.html
  site/content/docs/5.1/examples/cheatsheet/index.html
  site/content/docs/5.1/getting-started/introduction.md
Labels: v5, merge
