Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2021-02, with the labels that each got.

#622 Improve focus accessibility when fixed header/footer overlaps
  scss/_back-to-top.scss
  scss/_reboot.scss
  scss/_variables.scss
  site/assets/scss/_boosted.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.0/customize/options.md
  site/content/docs/5.0/getting-started/accessibility.md
Labels: accessibility, css, fix, on-hold, skip:ci, v5

#623 Missed bundlewatch check in latest PR
  .bundlewatch.config.json
Labels: chore, skip-changelog, skip:ci, v5

#624 fix: correct cross-env-shell that fails on Windows when run test is executed
  package.json
Labels: chore, fix, v4

#627 docs(release): missed beta1 occurrencies
  config.yml
Labels: chore, docs, skip:browserstack, skip:percy, v5

#630 Accessibility icon
  scss/orangeIcons.scss
Labels: brand, skip:ci, v4

#632 chore(merge v4-dev): latest patched commit → c34172143
  .bundlewatch.config.json
  .eslintrc.json
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  build/banner.js
  build/change-version.js
  build/vnu-jar.js
  js/dist/carousel.js
  js/src/tools/sanitizer.js
  js/tests/karma.conf.js
  js/tests/unit/.eslintrc.json
  package-lock.json
  package.json
  scss/_forms.scss
  scss/_variables.scss
  scss/mixins/_forms.scss
  site/.eslintrc.json
  site/assets/scss/docs.scss
  site/layouts/partials/bugify.html
  site/layouts/partials/callout-info-sanitizer.md
Labels: chore, dependencies, merge, v4

#633 Add fonts and logo to our package
  package.json
Labels: chore, skip:ci, v5

#634 Wrong versions in migration guide
  site/content/docs/5.0/migration.md
Labels: chore, docs, skip:ci, v5

#636 feat: Stepped Process: add the component from v4
  .bundlewatch.config.json
  scss/_stepped-process.scss
  scss/_variables.scss
  scss/boosted.scss
  site/content/docs/5.0/components/stepped-process.md
  site/content/docs/5.0/examples/cheatsheet-rtl/index.html
  site/content/docs/5.0/examples/cheatsheet/index.html
  site/content/docs/5.0/guidelines/navigation.md
  site/data/sidebar.yml
Labels: back-from-v4, brand, component, feature, v5
