Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2021-07, with the labels that each got.

#660 fix accordions padding / margin inconsistency
  scss/_card.scss
  site/content/docs/4.6/components/collapse.md
Labels: fix, v4

#697 fix(#694): replace the boosted.netlify doc links with /docs/5.0
  README.md
  site/content/docs/5.0/migration.md
Labels: docs, fix, v5

#732 Fix release 5.0.2
  package-lock.json
Labels: fix, v5

#736 fix(#735): separate local fonts from CDN in the starter template
  config.yml
  site/content/docs/5.0/getting-started/introduction.md
  site/content/docs/5.0/getting-started/rtl.md
Labels: backport-to-v4, fix, help wanted, v5

#738 fix(#735): separate local fonts from CDN in the starter template
  config.yml
  site/content/docs/4.6/getting-started/introduction.md
  site/content/docs/4.6/getting-started/rtl.md
Labels: backport-to-v4, fix, v4

#743 Social button fixed
  site/content/docs/5.0/components/buttons.md
Labels: fix, v5

#742 Toast color fix
  site/content/docs/5.0/components/toasts.md
Labels: fix, v5

#756 fix: update references of ff00dd to Nurovek
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
Labels: fix, v5
