Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2021-11, with the labels that each got.

#874 Bump tarteaucitronjs to 1.9.2 + workaround
  package-lock.json
  package.json
  site/assets/js/tac.js
Labels: v5, dependencies

#858 Chore/merge main@b991a6b
  .bundlewatch.config.json
  .cspell.json
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/pa11y.yml
  .github/workflows/percy.yml
  js/src/alert.js
  js/src/base-component.js
  js/src/button.js
  js/src/carousel.js
  js/src/collapse.js
  js/src/dom/data.js
  js/src/dom/event-handler.js
  js/src/dom/selector-engine.js
  js/src/dropdown.js
  js/src/modal.js
  js/src/offcanvas.js
  js/src/popover.js
  js/src/scrollspy.js
  js/src/tab.js
  js/src/toast.js
  js/src/tooltip.js
  js/src/util/backdrop.js
  js/src/util/focustrap.js
  js/src/util/index.js
  js/src/util/scrollbar.js
  js/src/util/swipe.js
  js/tests/unit/carousel.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/util/swipe.spec.js
  package-lock.json
  package.json
  scss/_tables.scss
  scss/mixins/_table-variants.scss
  site/content/docs/5.1/getting-started/download.md
Labels: v5, merge

#878 Chore/merge main@05f1b15
  .cspell.json
  package-lock.json
  package.json
  scss/_accordion.scss
  scss/_reboot.scss
  scss/forms/_form-control.scss
  scss/mixins/_container.scss
  scss/mixins/_grid.scss
  site/content/docs/5.1/about/license.md
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/components/offcanvas.md
  site/content/docs/5.1/content/images.md
  site/content/docs/5.1/examples/cheatsheet-rtl/index.html
  site/content/docs/5.1/examples/grid/index.html
  site/content/docs/5.1/getting-started/rtl.md
Labels: v5, merge

#877 Update Core team members list in v4
  site/data/core-team.yml
Labels: v4, docs, backport-to-v4

#885 Minor fixes around Navbar component
  scss/_navbar.scss
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/examples/cheatsheet-rtl/index.html
  site/content/docs/5.1/examples/cheatsheet/index.html
  site/content/docs/5.1/examples/navbars/index.html
Labels: v5, fix

#900 Merge Bootstrap main@367caea
  .gitignore
  README.md
  js/index.esm.js
  package-lock.json
  package.json
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/components/offcanvas.md
  site/content/docs/5.1/utilities/api.md
Labels: v5, merge

#904 Missing `.has-label` in some `.page-item` list elements
  site/content/docs/4.6/components/pagination.md
  site/content/docs/4.6/examples/news-template/index.html
Labels: v4, fix

#905 fix(#902): change page title padding top on md screens
  site/layouts/_default/docs.html
  site/layouts/_default/guidelines.html
Labels: v5, docs, fix

#864 Fix(forms): Border too thick for focused <select> in Forms > Custom styles in Chrome (#862)
  scss/forms/_form-select.scss
Labels: v5, fix, css

#883 feat(lineLength): Add class to limit line length
  .bundlewatch.config.json
  scss/_utilities.scss
  scss/_variables.scss
  site/content/docs/5.1/getting-started/accessibility.md
  site/content/docs/5.1/utilities/text.md
Labels: v5, utilities

#924 Remove concurrency, wait and timeout configurations in pa11y
  build/.pa11yci.json
Labels: v5, fix, github_actions

#921 Chore/merge main@9c01633
  package-lock.json
  package.json
  scss/_maps.scss
  scss/_variables.scss
  scss/boosted-grid.scss
  scss/boosted-reboot.scss
  scss/boosted-utilities.scss
  scss/boosted.scss
  site/content/docs/5.1/content/tables.md
  site/content/docs/5.1/customize/sass.md
  site/content/docs/5.1/migration.md
  site/content/docs/5.1/utilities/background.md
  site/content/docs/5.1/utilities/colors.md
Labels: v5, merge

#934 Layouts: add a top margin to the doc footer
  site/layouts/_default/docs.html
  site/layouts/_default/guidelines.html
  site/layouts/partials/footer.html
Labels: v5, docs, fix

#925 Line length : Fix descriptions
  site/content/docs/5.1/getting-started/accessibility.md
  site/content/docs/5.1/utilities/text.md
Labels: v5, fix

#935 Chore/merge main@fa33e83
  build/build-plugins.js
  build/change-version.js
  package-lock.json
  package.json
  site/content/docs/5.1/customize/color.md
  site/content/docs/5.1/customize/sass.md
  site/content/docs/5.1/examples/footers/index.html
  site/content/docs/5.1/utilities/api.md
Labels: v5, merge

#931 feat(lineLength): Add line length utility classes
  .bundlewatch.config.json
  scss/_variables.scss
  scss/utilities/_text.scss
  site/content/docs/4.6/getting-started/accessibility.md
  site/content/docs/4.6/utilities/text.md
Labels: v4, brand, backport-to-v4, utilities

#939 Chore/merge main@5290080
  js/src/modal.js
  js/src/popover.js
  js/src/tooltip.js
  js/src/util/template-factory.js
  js/tests/unit/modal.spec.js
  js/tests/unit/popover.spec.js
  js/tests/unit/tooltip.spec.js
  js/tests/unit/util/template-factory.spec.js
  scss/_close.scss
  scss/_reboot.scss
  scss/_root.scss
  site/assets/js/application.js
  site/content/docs/5.1/components/popovers.md
  site/content/docs/5.1/components/tooltips.md
  site/content/docs/5.1/content/typography.md
Labels: v5, merge

#932 fix(hideExamples): Hiding Bootstrap's examples from example page
  site/content/docs/5.1/examples/_index.md
  site/content/docs/5.1/examples/grid/index.html
  site/content/docs/5.1/examples/masonry/index.html
  site/data/examples.yml
  site/static/docs/5.1/assets/img/examples/grid.png
  site/static/docs/5.1/assets/img/examples/grid@2x.png
  site/static/docs/5.1/assets/img/examples/masonry.png
  site/static/docs/5.1/assets/img/examples/masonry@2x.png
Labels: v5, examples
