Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2021-10, with the labels that each got.

#829 chore(deps): bump mattermost/action-mattermost-notify from 1.0.0 to 1.1.0
  .github/workflows/notify.yml
Labels: dependencies, backport-to-v4, github_actions

#833 Update Core Team members list and change automatic assignee
  .github/CODEOWNERS
  .github/dependabot.yml
  site/data/core-team.yml
Labels: v5, docs, enhancement

#851 Fix (button): vertical alignment of icons within buttons in Firefox (#773)
  scss/_buttons.scss
Labels: v4, fix

#785 chore(a11y): add missing role='search' and type='search' in navbar component and examples
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/examples/carousel-rtl/index.html
  site/content/docs/5.1/examples/carousel/index.html
  site/content/docs/5.1/examples/cheatsheet-rtl/index.html
  site/content/docs/5.1/examples/cheatsheet/index.html
  site/content/docs/5.1/examples/headers/index.html
  site/content/docs/5.1/examples/navbar-fixed/index.html
  site/content/docs/5.1/examples/navbar-static/index.html
  site/content/docs/5.1/examples/navbars/index.html
  site/content/docs/5.1/examples/offcanvas-navbar/index.html
  site/content/docs/5.1/examples/sticky-footer-navbar/index.html
Labels: v5, accessibility, enhancement
