Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2022-01, with the labels that each got.

#1010 Buttons with dark background (`.btn-inverse`)
  .bundlewatch.config.json
  scss/_button-group.scss
  scss/_buttons.scss
  scss/_dropdown.scss
  site/content/docs/5.1/components/buttons.md
  site/content/docs/5.1/components/dropdowns.md
Labels: v5, feature

#1009 [Docs] Modify docs template design for examples and guidelines
  site/content/docs/5.1/guidelines/_index.md
  site/layouts/_default/guidelines.html
  site/layouts/_default/single.html
Labels: v5, brand, docs, enhancement

#1014 chore/merge main@cebb843
  LICENSE
  NOTICE.txt
  README.md
  build/build-plugins.js
  build/change-version.js
  build/generate-sri.js
  build/vnu-jar.js
  build/zip-examples.js
  nuget/boosted.nuspec
  nuget/boosted.sass.nuspec
  package-lock.json
  package.json
  scss/boosted-grid.scss
  scss/boosted-reboot.scss
  scss/boosted-utilities.scss
  scss/boosted.scss
  site/assets/js/application.js
  site/assets/scss/docs.scss
Labels: v5, merge

#1013 chore(merge-v4-dev): patched commit → a3d14bb
  site/content/docs/4.6/components/toasts.md
Labels: v4, merge

#1018 Chore/merge v4 dev@349a373
  LICENSE
  NOTICE.txt
  README.md
  build/build-plugins.js
  build/change-version.js
  build/docs-rtl.js
  build/generate-sri.js
  build/vnu-jar.js
  build/zip-examples.js
  config.yml
  nuget/boosted.nuspec
  nuget/boosted.sass.nuspec
  package-lock.json
  package.json
  scss/boosted-grid.scss
  scss/boosted-reboot.scss
  scss/boosted.scss
  site/assets/js/application.js
  site/assets/scss/docs.scss
  site/content/docs/4.6/components/carousel.md
  site/content/docs/4.6/components/navs.md
  site/content/docs/4.6/components/orange-footer.md
  site/layouts/partials/boostwatch/ofooter.html
Labels: v4, merge

#1024 Chore/merge main@e8f4cba
  js/src/offcanvas.js
  js/tests/unit/offcanvas.spec.js
  scss/_offcanvas.scss
  site/content/docs/5.1/components/list-group.md
  site/content/docs/5.1/components/offcanvas.md
  site/content/docs/5.1/migration.md
Labels: v5, merge

#1020 fix(#1019): modify buttons icons padding
  scss/_buttons.scss
Labels: v5, fix

#1033 Chore: Merge `main` @1726041
  config.yml
  package-lock.json
  package.json
Labels: v5, merge

#1037 Merge main@c99fa6c
  .cspell.json
  build/build-plugins.js
  js/src/util/index.js
  js/tests/unit/util/index.spec.js
  package-lock.json
  package.json
  site/content/docs/5.1/components/modal.md
  site/content/docs/5.1/content/reboot.md
  site/content/docs/5.1/customize/sass.md
  site/content/docs/5.1/getting-started/rtl.md
  site/content/docs/5.1/migration.md
Labels: v5, merge

#1043 Chore: merge main@cd20834
  README.md
  package-lock.json
  package.json
Labels: v5, merge

#1051 Enhance split button doc example and fix button wording
  site/content/docs/4.6/components/dropdowns.md
Labels: v4, docs, fix

#1064 Docs: use `.btn-inverse` for download button in main header
  site/layouts/partials/docs-navbar.html
Labels: documentation, fix

#1063 Merge main@c1222d6
  package-lock.json
  package.json
  site/content/docs/5.1/examples/dropdowns/dropdowns.css
  site/content/docs/5.1/examples/features/features.css
  site/content/docs/5.1/examples/footers/footers.css
  site/content/docs/5.1/examples/headers/headers.css
  site/content/docs/5.1/examples/heroes/heroes.css
  site/content/docs/5.1/examples/list-groups/list-groups.css
  site/content/docs/5.1/examples/modals/modals.css
  site/content/docs/5.1/examples/navbars/index.html
  site/content/docs/5.1/examples/navbars/navbar.css
  site/content/docs/5.1/examples/sidebars/index.html
  site/content/docs/5.1/examples/sidebars/sidebars.css
  site/layouts/_default/examples.html
Labels: v5, merge

#1041 Rollback the grow spinners
  .bundlewatch.config.json
  scss/_spinners.scss
  site/content/docs/5.1/components/spinners.md
Labels: v5, feature, back-from-v4

#1005 Drop `delay-cli` to avoid CVE-2021-33623 and use `sirv-cli`
  .github/workflows/pa11y.yml
  package-lock.json
  package.json
Labels: v5, dependencies, security
