Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2022-02, with the labels that each got.

#1070 FIX: Restore line heights var values by fixing `calc(divide())` operations
  scss/_variables.scss
Labels: v4, fix

#1039 Orange stepbar
  scss/_o-step-bar.scss
  scss/_variables.scss
  site/content/docs/4.6/components/stepbar.md
Labels: brand, backport-to-v4

#1079 Grid fix
  site/content/docs/4.6/examples/grid/index.html
Labels: v4, documentation, fix

#1081 fix(forms): vertically align labels for switches
  scss/_variables.scss
  scss/forms/_form-check.scss
Labels: v5, fix

#1083 fix(docs): make visible 'Design guidelines' menu item when the page is active
  site/layouts/partials/docs-navbar.html
Labels: v5, documentation, fix

#1082 fix(forms): black outline for focused switches
  scss/forms/_form-check.scss
Labels: v5, fix

#1080 Chore/merge main@dc09509
  js/src/dom/event-handler.js
  js/src/dropdown.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/popover.spec.js
  package-lock.json
  package.json
  site/content/docs/5.1/forms/layout.md
Labels: v5, merge

#658 fix dropdowns on `.bg-dark`
  scss/_dropdown.scss
  scss/_variables.scss
Labels: v4, fix

#1087 fix(accordion): Remove active text color on focus
  scss/_accordion.scss
Labels: v5, fix

#1092 Chore/merge-main@8f11c52
  package-lock.json
  package.json
Labels: v5, merge

#1096 Chore/merge main@a794219
  build/.pa11yci.json
  js/tests/unit/dropdown.spec.js
  js/tests/visual/dropdown.html
  scss/_badge.scss
  site/content/docs/5.1/components/badge.md
  site/content/docs/5.1/components/scrollspy.md
  site/content/docs/5.1/customize/css-variables.md
Labels: v5, merge

#1038 Dark texts
  .bundlewatch.config.json
  scss/_root.scss
  scss/_variables.scss
  scss/mixins/_utilities.scss
  site/content/docs/5.1/examples/checkout-rtl/index.html
  site/content/docs/5.1/examples/checkout/index.html
  site/content/docs/5.1/examples/dashboard-rtl/index.html
  site/content/docs/5.1/examples/dashboard/index.html
  site/content/docs/5.1/examples/headers/index.html
  site/content/docs/5.1/examples/heroes/index.html
  site/content/docs/5.1/examples/sidebars/index.html
  site/content/docs/5.1/examples/sticky-footer-navbar/index.html
  site/content/docs/5.1/examples/sticky-footer/index.html
Labels: v5, brand, feature

#1012 Alerts with dark background
  site/content/docs/5.1/components/alerts.md
  site/content/docs/5.1/components/close-button.md
Labels: v5, brand, feature

#1111 fix: update calibreapp/image-actions reference in optimize workflow
  .github/workflows/optimize.yml
Labels: fix, github_actions

#1021 Adjusting dark dropdowns
  scss/_variables.scss
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/customize/color.md
Labels: v5, brand, feature

#860 Quantity Selector
  .bundlewatch.config.json
  js/index.esm.js
  js/index.umd.js
  js/src/quantity-selector.js
  js/tests/unit/quantity-selector.spec.js
  scss/_forms.scss
  scss/_variables.scss
  scss/forms/_quantity-selector.scss
  scss/mixins/_forms.scss
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/customize/overview.md
  site/content/docs/5.1/forms/overview.md
  site/content/docs/5.1/forms/quantity-selector.md
  site/content/docs/5.1/forms/validation.md
  site/content/docs/5.1/getting-started/introduction.md
  site/data/sidebar.yml
Labels: v5, feature

#1113 chore/merge-main @42da2b9
  .bundlewatch.config.json
  build/build-plugins.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/scrollspy.spec.js
  js/tests/unit/tooltip.spec.js
  js/tests/unit/util/swipe.spec.js
  js/tests/unit/util/template-factory.spec.js
  package-lock.json
  package.json
  scss/_dropdown.scss
  site/assets/scss/_algolia.scss
  site/assets/scss/_subnav.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/examples/dropdowns/index.html
Labels: v5, merge
