Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2022-04, with the labels that each got.

#1144 fix(forms): change the margin left value between the required symbol and the label
  scss/_variables.scss
  scss/forms/_form-check.scss
  scss/forms/_labels.scss
Labels: v5, brand, backport-to-v4, fix

#1177 fix(forms): change the margin left value between the required symbol and the label
  scss/_forms.scss
  scss/_o-forms.scss
  scss/_variables.scss
Labels: v4, fix

#1155 fix(pagination): change background position of arrow icon, and global…
  scss/_pagination.scss
Labels: v5, backport-to-v4, fix

#1180 fix(cspell): add 'Analyser'
  .cspell.json
Labels: v5, fix, github_actions

#1099 Global headers 710
  .bundlewatch.config.json
  build/vnu-jar.js
  js/index.esm.js
  js/index.umd.js
  js/src/collapse.js
  js/src/orange-navbar.js
  js/tests/unit/orange-navbar.spec.js
  scss/_navbar.scss
  scss/_orange-navbar.scss
  scss/_variables.scss
  site/assets/scss/_boosted.scss
  site/assets/scss/_subnav.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/components/orange-navbar.md
  site/content/docs/5.1/examples/navbar-sticky/index.html
  site/content/docs/5.1/examples/navbar-sticky/navbar-sticky.css
  site/content/docs/5.1/examples/navbar-sticky/navbar-sticky.js
  site/content/docs/5.1/examples/navbars/index.html
  site/content/docs/5.1/getting-started/introduction.md
  site/content/docs/5.1/migration.md
  site/data/examples.yml
  site/layouts/partials/docs-navbar.html
  site/layouts/shortcodes/orange-global-headers.html
  site/layouts/shortcodes/orange-supra.html
  site/static/docs/5.1/assets/brand/OBS-logo.svg
  site/static/docs/5.1/assets/img/examples/navbar-sticky.png
  site/static/docs/5.1/assets/img/examples/navbar-sticky@2x.png
  site/static/docs/5.1/assets/img/examples/navbars.png
  site/static/docs/5.1/assets/img/examples/navbars@2x.png
Labels: v5, brand, back-from-v4

#1188 chore(docs): reorder alphabetically list of components
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/customize/overview.md
  site/content/docs/5.1/getting-started/introduction.md
Labels: v5, docs, backport-to-v4

#1195 chore(docs): reorder alphabetically list of components
  site/content/docs/4.6/about/boosted-history.md
  site/content/docs/4.6/getting-started/introduction.md
Labels: v4, docs, enhancement

#1197 chore(dependencies): bump tarteaucitronjs from 1.9.5 to 1.9.6
  package-lock.json
  package.json
Labels: v5, dependencies

#1181 chore/merge-main@e342142
  .bundlewatch.config.json
  scss/_accordion.scss
  scss/_card.scss
  scss/_modal.scss
  scss/_nav.scss
  scss/_variables.scss
  site/content/docs/5.1/components/accordion.md
  site/content/docs/5.1/components/card.md
  site/content/docs/5.1/components/modal.md
  site/content/docs/5.1/components/navs-tabs.md
Labels: v5, merge

#1203 chore/merge-main@e206a60
  .bundlewatch.config.json
  config.yml
  js/src/tab.js
  js/tests/unit/tab.spec.js
  package-lock.json
  package.json
  scss/_accordion.scss
  scss/_badge.scss
  scss/_breadcrumb.scss
  scss/_button-group.scss
  scss/_buttons.scss
  scss/_list-group.scss
  scss/_nav.scss
  scss/_navbar.scss
  scss/_pagination.scss
  scss/_placeholders.scss
  scss/_popover.scss
  scss/_reboot.scss
  scss/_root.scss
  scss/_spinners.scss
  scss/_toasts.scss
  scss/_utilities.scss
  scss/_variables.scss
  scss/forms/_form-check.scss
  scss/helpers/_vr.scss
  scss/mixins/_buttons.scss
  site/assets/js/application.js
  site/assets/scss/_boosted.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_content.scss
  site/assets/scss/_syntax.scss
  site/content/docs/5.1/components/accordion.md
  site/content/docs/5.1/components/alerts.md
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/components/modal.md
  site/content/docs/5.1/components/navbar.md
  site/content/docs/5.1/components/navs-tabs.md
  site/content/docs/5.1/components/popovers.md
  site/content/docs/5.1/components/toasts.md
  site/content/docs/5.1/components/tooltips.md
  site/content/docs/5.1/examples/dropdowns/index.html
  site/content/docs/5.1/examples/features/features.css
  site/content/docs/5.1/examples/features/index.html
  site/content/docs/5.1/examples/list-groups/index.html
  site/content/docs/5.1/examples/modals/index.html
  site/content/docs/5.1/examples/sidebars/sidebars.css
  site/content/docs/5.1/layout/breakpoints.md
  site/content/docs/5.1/utilities/borders.md
  site/data/sidebar.yml
  site/layouts/_default/examples.html
  site/layouts/partials/scripts.html
Labels: v5, merge

#1207 chore/merge main@26ea6f1
  .bundlewatch.config.json
  js/src/dom/manipulator.js
  js/src/dropdown.js
  js/src/scrollspy.js
  js/tests/unit/dom/manipulator.spec.js
  js/tests/unit/scrollspy.spec.js
  package-lock.json
  package.json
  scss/_button-group.scss
  scss/_list-group.scss
  scss/_modal.scss
  scss/_popover.scss
  scss/_tooltip.scss
  scss/_variables.scss
  site/.eslintrc.json
  site/assets/js/application.js
  site/assets/js/search.js
  site/assets/js/tac.js
  site/assets/scss/_component-examples.scss
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/components/navs-tabs.md
  site/content/docs/5.1/components/scrollspy.md
  site/content/docs/5.1/examples/cheatsheet/cheatsheet.js
  site/content/docs/5.1/examples/cheatsheet/index.html
  site/content/docs/5.1/examples/checkout/form-validation.js
  site/content/docs/5.1/examples/dashboard-rtl/dashboard.js
  site/content/docs/5.1/examples/dashboard/dashboard.js
  site/content/docs/5.1/examples/navbar-sticky/navbar-sticky.js
  site/content/docs/5.1/examples/offcanvas-navbar/offcanvas.js
  site/content/docs/5.1/examples/sidebars/sidebars.js
  site/content/docs/5.1/getting-started/parcel.md
  site/content/docs/5.1/layout/containers.md
  site/content/docs/5.1/migration.md
  site/layouts/partials/scripts.html
  site/static/docs/5.1/assets/js/tarteaucitron.services.js
  site/static/docs/5.1/assets/js/validate-forms.js
Labels: v5, merge

#1146 Provide a pause button for Carousels
  .bundlewatch.config.json
  js/src/carousel.js
  js/tests/unit/carousel.spec.js
  scss/_carousel.scss
  scss/_variables.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.1/components/carousel.md
Labels: v5, accessibility, back-from-v4

#1213 fix(docs): replace '..' by '…' in the documentation title
  config.yml
Labels: v5, accessibility, docs, backport-to-v4, fix

#1216 feat(utilities): reintroduce `.text-uppercase`
  scss/_utilities.scss
  site/content/docs/5.1/utilities/text.md
Labels: v5, backport-to-v4, utilities

#1218 feat(utilities): reintroduce `.text-uppercase`
  scss/utilities/_text.scss
  site/content/docs/4.6/utilities/text.md
Labels: v4, utilities

#1219 fix(cookies): hide 'Cookies management panel' in the header
  site/assets/scss/_tarteaucitron.scss
Labels: v5, fix

#970 Footer component
  .bundlewatch.config.json
  scss/_footer.scss
  scss/_variables.scss
  scss/boosted.scss
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/components/footer.md
  site/content/docs/5.1/components/orange-footer.md
  site/content/docs/5.1/examples/footers/footers.css
  site/content/docs/5.1/examples/footers/index.html
  site/content/docs/5.1/getting-started/introduction.md
  site/content/docs/5.1/migration.md
  site/data/sidebar.yml
  site/layouts/shortcodes/orange-footer.html
  site/static/docs/5.1/assets/img/boosted-sprite.svg
  site/static/docs/5.1/assets/img/examples/footers.png
  site/static/docs/5.1/assets/img/examples/footers@2x.png
Labels: v5, brand, component

#1223 chore(meta): update contributing guideline to remove Bootstrap refs
  .github/CONTRIBUTING.md
Labels: meta
