Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2022-03, with the labels that each got.

#1023 :new: Sticker component
  .bundlewatch.config.json
  .cspell.json
  scss/_sticker.scss
  scss/_variables.scss
  scss/boosted.scss
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/components/sticker.md
  site/content/docs/5.1/examples/stickers/index.html
  site/data/examples.yml
  site/data/sidebar.yml
  site/static/docs/5.1/assets/img/boosted-sprite.svg
  site/static/docs/5.1/assets/img/examples/stickers.png
  site/static/docs/5.1/assets/img/examples/stickers@2x.png
Labels: v5, brand, component

#1017 Docs(navs-tabs): add nested tabs
  .bundlewatch.config.json
  build/.pa11yci.json
  scss/_nav.scss
  scss/_variables.scss
  site/content/docs/5.1/components/navs-tabs.md
Labels: v5, component

#1134 chore(docs): update Core team members list
  site/data/core-team.yml
Labels: v4, chore, documentation

#1133 chore(docs): update Core team members list
  site/data/core-team.yml
Labels: v5, chore, documentation

#1135 docs:Add hannah to core team in doc
  site/data/core-team.yml
Labels: v5, documentation, backport-to-v4

#1136 docs:Add Hannah to core team membres
  site/data/core-team.yml
Labels: v4, chore, documentation

#1124 implement default focus-visible
  scss/_reboot.scss
Labels: accessibility, css, enhancement

#1132 Chore: merge main @e84aadb
  .bundlewatch.config.json
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/cspell.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/pa11y.yml
  .github/workflows/percy.yml
  README.md
  js/src/carousel.js
  js/src/dropdown.js
  js/src/modal.js
  js/src/offcanvas.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/offcanvas.spec.js
  package-lock.json
  package.json
  scss/_accordion.scss
  scss/_alert.scss
  scss/_badge.scss
  scss/_dropdown.scss
  scss/_functions.scss
  scss/_maps.scss
  scss/_nav.scss
  scss/_navbar.scss
  scss/_popover.scss
  scss/_root.scss
  scss/_tables.scss
  scss/_tooltip.scss
  scss/_utilities.scss
  scss/_variables.scss
  scss/mixins/_forms.scss
  scss/mixins/_utilities.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_content.scss
  site/content/docs/5.1/components/dropdowns.md
  site/content/docs/5.1/components/offcanvas.md
  site/content/docs/5.1/components/toasts.md
  site/content/docs/5.1/content/tables.md
  site/content/docs/5.1/examples/carousel/carousel.css
  site/content/docs/5.1/examples/carousel/carousel.rtl.css
  site/content/docs/5.1/migration.md
  site/content/docs/5.1/utilities/api.md
  site/content/docs/5.1/utilities/borders.md
  site/data/translations.yml
Labels: v5, merge

#987 Handle `.container-fluid` to follow brand
  .bundlewatch.config.json
  scss/_containers.scss
  scss/_orange-navbar.scss
  scss/_variables.scss
  scss/mixins/_container.scss
  site/assets/scss/_content.scss
  site/content/docs/5.1/examples/cards/index.html
  site/content/docs/5.1/examples/footers/index.html
  site/content/docs/5.1/examples/grid/index.html
  site/content/docs/5.1/examples/masonry/index.html
  site/content/docs/5.1/guidelines/_index.md
  site/content/docs/5.1/layout/containers.md
  site/layouts/_default/single.html
  site/layouts/partials/footer.html
  site/layouts/partials/home/masthead-followup.html
  site/layouts/partials/home/masthead.html
  site/layouts/shortcodes/orange-supra.html
Labels: v5, fix

#1143 Chore/merge main@3a57da4
  .bundlewatch.config.json
  js/src/dropdown.js
  scss/_dropdown.scss
  scss/_popover.scss
  scss/_root.scss
  scss/_tooltip.scss
  scss/_variables.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.1/components/popovers.md
  site/content/docs/5.1/components/tooltips.md
  site/content/docs/5.1/migration.md
Labels: v5, merge
