Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2022-06, with the labels that each got.

#1242 Carousel navigation focus
  scss/_carousel.scss
  scss/_variables.scss
  site/content/docs/5.1/utilities/borders.md
Labels: v5, brand, component

#1284 Chore/merge-v4-dev-@261418
  .bundlewatch.config.json
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/dart-sass.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .gitignore
  js/src/scrollspy.js
  js/src/tab.js
  js/tests/unit/tab.js
  js/tests/visual/dropdown.html
  js/tests/visual/tab.html
  package-lock.json
  package.json
  scss/_button-group.scss
  scss/_custom-forms.scss
  scss/_nav.scss
  scss/_navbar.scss
  scss/_o-nav-local.scss
  scss/_o-tabs.scss
  scss/_reboot.scss
  scss/_spinners.scss
  scss/_type.scss
  scss/mixins/_forms.scss
  site/assets/scss/_boosted-docs.scss
  site/content/docs/4.6/components/dropdowns.md
  site/content/docs/4.6/components/navs.md
Labels: v4, merge

#1285 Remove back-to-top from small pages
  site/assets/js/application.js
Labels: v5, docs, fix

#1252 Breadcrumb : add CSS var
  scss/_breadcrumb.scss
  scss/_variables.scss
Labels: v5, css, enhancement

#1273 fix(back-to-top): icon and label positioning
  scss/_back-to-top.scss
Labels: v5, fix

#1254 Progress : Add CSS var
  scss/_progress.scss
  scss/_variables.scss
Labels: v5, css, enhancement

#1259 Title bars : Add CSS var
  scss/_title-bars.scss
  scss/_variables.scss
Labels: v5, css, enhancement

#1253 Cards : Adding CSS var
  scss/_card.scss
  scss/_variables.scss
Labels: v5, css, enhancement

#1303 fix(build): force swiper reinstall
  package-lock.json
Labels: v4, fix, build

#1165 Fixes for alerts
  scss/_alert.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.1/components/alerts.md
Labels: v5, enhancement

#1258 Back to top : Add CSS variables
  .bundlewatch.config.json
  scss/_back-to-top.scss
  site/content/docs/5.1/components/back-to-top.md
  site/content/docs/5.1/migration.md
  site/layouts/partials/footer.html
Labels: v5, css, enhancement

#1304 Chore/merge-v4-dev@6fd2030
  js/tests/unit/dropdown.js
  js/tests/unit/tab.js
  js/tests/visual/dropdown.html
  js/tests/visual/scrollspy.html
  js/tests/visual/tab.html
  scss/_transitions.scss
  scss/_variables.scss
  site/assets/scss/_boosted-docs.scss
  site/content/docs/4.6/components/breadcrumb.md
  site/content/docs/4.6/components/button-group.md
  site/content/docs/4.6/components/collapse.md
  site/content/docs/4.6/components/dropdowns.md
  site/content/docs/4.6/components/navbar.md
  site/content/docs/4.6/components/navs.md
  site/content/docs/4.6/examples/jumbotron/index.html
  site/content/docs/4.6/examples/navbar-bottom/index.html
  site/content/docs/4.6/examples/navbars/index.html
  site/content/docs/4.6/examples/offcanvas/index.html
  site/content/docs/4.6/examples/starter-template/index.html
  site/content/docs/4.6/getting-started/accessibility.md
  site/layouts/partials/docs-navbar.html
Labels: v4, merge

#1340 Card cap color fix
  scss/_card.scss
Labels: help wanted, v5, fix, css

#1348 chore(search): matching information with v5
  site/assets/js/search.js
Labels: v4, chore
