Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2022-05, with the labels that each got.

#1226 fix(color): add indigo to colors (existing but not documented).
  site/content/docs/5.1/customize/color.md
Labels: v5, docs, fix

#1179 fix(pagination): set margin between numbers to 0
  scss/_pagination.scss
  scss/_variables.scss
Labels: v5, backport-to-v4, fix

#1042 Clever sticky footer
  site/assets/scss/_boosted.scss
  site/assets/scss/_footer.scss
Labels: v5, docs, fix

#1228 fix(doc): add checks and radios without labels
  site/content/docs/5.1/forms/checks-radios.md
Labels: v5, docs, fix

#956 Title bars
  .bundlewatch.config.json
  scss/_title-bars.scss
  scss/_variables.scss
  scss/boosted.scss
  site/content/docs/5.1/about/overview.md
  site/content/docs/5.1/components/title-bars.md
  site/content/docs/5.1/examples/title-bars/index.html
  site/content/docs/5.1/examples/title-bars/title-bars.css
  site/data/examples.yml
  site/data/sidebar.yml
  site/layouts/_default/single.html
  site/static/docs/5.1/assets/img/examples/title-bars.png
  site/static/docs/5.1/assets/img/examples/title-bars@2x.png
  site/static/docs/5.1/assets/img/title-bars-illustrations/illustration-1024.png
  site/static/docs/5.1/assets/img/title-bars-illustrations/illustration-1280.png
  site/static/docs/5.1/assets/img/title-bars-illustrations/illustration-1440.png
  site/static/docs/5.1/assets/img/title-bars-illustrations/illustration-320.png
  site/static/docs/5.1/assets/img/title-bars-illustrations/illustration-480.png
  site/static/docs/5.1/assets/img/title-bars-illustrations/illustration-768.png
Labels: v5, brand, component

#1244 chore(meta): remove CODEOWNERS content
  .github/CODEOWNERS
Labels: meta

#1246 chore: update core team members list
  site/data/core-team.yml
Labels: v4, docs

#1245 chore: update core team members list
  site/data/core-team.yml
Labels: v5, docs

#1255 🎤 A dollar is what I need
  scss/_alert.scss
  site/assets/scss/_syntax.scss
Labels: v5, fix, css

#1251 feat(stickers): Add CSS vars for $sticker-
  scss/_sticker.scss
  site/content/docs/5.1/components/sticker.md
Labels: v5, css, enhancement

#1269 fix(pagination): Remove space between pagination numbers in v4
  scss/_pagination.scss
  scss/_variables.scss
Labels: v4, backport-to-v4, fix

#1248 Patching list color
  scss/_reboot.scss
Labels: accessibility, backport-to-v4, css

#1291 Patching list color v4
  scss/_reboot.scss
Labels: v4, accessibility, backport-to-v4, fix, css
