Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2023-03, with the labels that each got.

#1763 Carousel's pause/play button must be placed first
  .bundlewatch.config.json
  js/src/carousel.js
  scss/_carousel.scss
  scss/_variables.scss
  site/content/docs/5.3/components/carousel.md
  site/content/docs/5.3/migration.md
Labels: v5, feature, accessibility, OK accessibility, OK design

#1862 Chore merge from 17f14ac
  js/tests/visual/toast.html
  js/tests/visual/tooltip.html
  scss/_list-group.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables.scss
  site/assets/scss/_navbar.scss
  site/assets/scss/_search.scss
  site/assets/scss/_tarteaucitron.scss
  site/content/docs/5.3/components/card.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/navbar.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/typography.md
  site/content/docs/5.3/customize/color.md
  site/content/docs/5.3/customize/overview.md
  site/content/docs/5.3/examples/_index.md
  site/content/docs/5.3/examples/masonry/index.html
  site/content/docs/5.3/extend/icons.md
  site/content/docs/5.3/forms/form-control.md
  site/content/docs/5.3/forms/overview.md
  site/content/docs/5.3/getting-started/browsers-devices.md
  site/content/docs/5.3/layout/containers.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/api.md
  site/content/docs/5.3/utilities/borders.md
  site/content/docs/5.3/utilities/colors.md
  site/content/docs/5.3/utilities/text.md
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/home/components-utilities.html
  site/layouts/partials/home/get-started.html
  site/layouts/partials/home/masthead.html
  site/layouts/partials/home/plugins.html
  site/layouts/shortcodes/example.html
Labels: v5, merge

#1874 Fix US Vs UK english
  js/src/orange-navbar.js
Labels: v5, docs, fix

#1872 Chore merge from 436de31
  js/tests/visual/input.html
  package-lock.json
  package.json
  scss/_carousel.scss
  scss/_maps.scss
  scss/_root.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/forms/_form-control.scss
  scss/mixins/_utilities.scss
  scss/tests/mixins/_color-modes.test.scss
  site/assets/scss/_callouts.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/carousel.md
  site/content/docs/5.3/components/collapse.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/popovers.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/content/figures.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/content/typography.md
  site/content/docs/5.3/customize/color-modes.md
  site/content/docs/5.3/customize/color.md
  site/content/docs/5.3/forms/checks-radios.md
  site/content/docs/5.3/forms/input-group.md
  site/content/docs/5.3/forms/overview.md
  site/content/docs/5.3/forms/quantity-selector.md
  site/content/docs/5.3/forms/range.md
  site/content/docs/5.3/forms/select.md
  site/content/docs/5.3/forms/validation.md
  site/content/docs/5.3/getting-started/rtl.md
  site/content/docs/5.3/helpers/color-background.md
  site/content/docs/5.3/helpers/icon-link.md
  site/content/docs/5.3/helpers/stacks.md
  site/content/docs/5.3/helpers/vertical-rule.md
  site/content/docs/5.3/layout/columns.md
  site/content/docs/5.3/layout/grid.md
  site/content/docs/5.3/layout/gutters.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/background.md
  site/content/docs/5.3/utilities/borders.md
  site/content/docs/5.3/utilities/colors.md
  site/content/docs/5.3/utilities/sizing.md
  site/content/docs/5.3/utilities/spacing.md
  site/content/docs/5.3/utilities/text.md
  site/layouts/_default/docs.html
  site/layouts/partials/callouts/warning-color-assistive-technologies.md
  site/layouts/shortcodes/scss-docs.html
Labels: v5, merge

#1873 Chore merge from c735b2e to 9dd42e1
  README.md
  config.yml
  js/src/modal.js
  js/src/offcanvas.js
  js/tests/unit/tooltip.spec.js
  package-lock.json
  package.json
  scss/_alert.scss
  scss/_utilities.scss
  scss/_variables.scss
  scss/tests/utilities/_api.test.scss
  site/assets/js/search.js
  site/assets/scss/_scrolling.scss
  site/assets/scss/_toc.scss
  site/assets/scss/docs.scss
  site/content/docs/5.3/components/navs-tabs.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/getting-started/introduction.md
  site/content/docs/5.3/getting-started/javascript.md
  site/content/docs/5.3/migration.md
  site/layouts/_default/docs.html
  site/layouts/partials/analytics-body.html
Labels: v5, merge

#1658 Modal: fix margin between text and buttons
  scss/_modal.scss
  scss/_variables.scss
  site/content/docs/5.3/migration.md
Labels: v5, fix, passed design review

#1882 Chore merge from 8fddb9f to a3f8480
  js/tests/unit/collapse.spec.js
  package-lock.json
  package.json
  scss/_buttons.scss
  scss/_navbar.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/forms/_form-select.scss
  scss/helpers/_icon-link.scss
  site/assets/scss/_clipboard-js.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_masthead.scss
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/customize/color-modes.md
  site/content/docs/5.3/extend/approach.md
  site/content/docs/5.3/forms/validation.md
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/helpers/icon-link.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/colors.md
  site/content/docs/5.3/utilities/link.md
  site/layouts/_default/examples.html
  site/layouts/partials/home/plugins.html
  site/layouts/partials/icons.html
  site/static/docs/5.3/assets/img/guides/parcel-dev-server-boosted.png
  site/static/docs/5.3/assets/img/guides/parcel-dev-server.png
  site/static/docs/5.3/assets/img/guides/vite-dev-server-boosted.png
  site/static/docs/5.3/assets/img/guides/vite-dev-server.png
  site/static/docs/5.3/assets/img/guides/webpack-dev-server-boosted.png
  site/static/docs/5.3/assets/img/guides/webpack-dev-server.png
  site/static/docs/5.3/assets/js/color-modes.js
Labels: v5, chore, merge

#1884 fix(docs): modal with image example wasn't rendered
  site/content/docs/5.3/components/modal.md
Labels: v5, docs, fix

#1709 Add new info callout for ODS recommendation
  site/assets/scss/_alerts.scss
  site/assets/scss/docs.scss
  site/content/docs/5.3/components/badge.md
  site/content/docs/5.3/components/breadcrumb.md
  site/content/docs/5.3/components/button-group.md
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/carousel.md
  site/content/docs/5.3/components/collapse.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/navbar.md
  site/content/docs/5.3/components/navs-tabs.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/components/scrollspy.md
  site/content/docs/5.3/components/spinners.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/reboot.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/customize/color.md
  site/content/docs/5.3/forms/input-group.md
  site/content/docs/5.3/forms/layout.md
  site/content/docs/5.3/getting-started/introduction.md
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/helpers/icon-link.md
  site/content/docs/5.3/utilities/link.md
  site/layouts/shortcodes/design-callout-alert.html
  site/layouts/shortcodes/ods-incompatibility-alert.html
Labels: v5, docs

#1887 Chore merge main from 2a2c4ab
  .github/workflows/docs.yml
  site/assets/scss/_scrolling.scss
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/placeholders.md
  site/content/docs/5.3/components/scrollspy.md
  site/content/docs/5.3/customize/color-modes.md
  site/layouts/_default/docs.html
  site/layouts/shortcodes/js-dismiss.html
  site/layouts/shortcodes/scss-docs.html
Labels: v5, chore, merge

#1901 Chore merge from c57be44 to adf7b8d
  .github/workflows/docs.yml
  .gitignore
  .npmrc
  .stylelintrc
  .stylelintrc.json
  js/src/tab.js
  js/tests/unit/tab.spec.js
  js/tests/visual/input.html
  package-lock.json
  package.json
  site/assets/scss/_masthead.scss
  site/assets/scss/_variables.scss
  site/assets/scss/docs.scss
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/placeholders.md
  site/content/docs/5.3/content/images.md
  site/content/docs/5.3/examples/.stylelintrc
  site/static/docs/5.3/assets/js/color-modes.js
Labels: v5, chore, merge

#1889 Fix double x-border in `scss-docs` shortcode
  site/layouts/shortcodes/scss-docs.html
Labels: v5, docs, fix

#1885 Supra: fix spacing example in small viewport
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/examples/form/index.html
  site/layouts/shortcodes/orange-global-headers.html
Labels: v5, brand, fix

#1719 fix(forms): vertical alignment of invalid feedback icon
  scss/mixins/_forms.scss
Labels: v5, fix, css, passed design review

#1905 Remove unnecessary class for better consistency of the migration guide
  site/content/docs/5.3/migration.md
Labels: v5, docs, fix

#1906 Main jd chore merge from fe786cd to 5414880
  package-lock.json
  package.json
  site/content/docs/5.3/helpers/icon-link.md
Labels: chore, merge

#1858 🟡 ⚫ Boosted dark mode prototype
  scss/_variables-dark.scss
  scss/_variables.scss
  site/assets/scss/_boosted.scss
  site/assets/scss/_callouts.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.3/components/tags.md
  site/content/docs/5.3/components/title-bars.md
  site/content/docs/5.3/examples/form/index.html
  site/content/docs/5.3/examples/title-bars/index.html
  site/layouts/_default/single.html
Labels: v5, brand, css

#1907 Chore merge main from 2d0c94c to a6d8aa8
  site/assets/scss/_content.scss
  site/assets/scss/_masthead.scss
  site/assets/scss/_scrolling.scss
  site/content/docs/5.3/utilities/object-fit.md
  site/layouts/shortcodes/placeholder.html
  site/static/docs/5.3/assets/js/color-modes.js
Labels: v5, chore, merge

#1916 Chore merge from 43ec90b to b3faa0c
  .github/dependabot.yml
  js/index.esm.js
  js/index.umd.js
  js/src/alert.js
  js/src/base-component.js
  js/src/button.js
  js/src/carousel.js
  js/src/collapse.js
  js/src/dom/data.js
  js/src/dom/event-handler.js
  js/src/dom/manipulator.js
  js/src/dom/selector-engine.js
  js/src/dropdown.js
  js/src/modal.js
  js/src/offcanvas.js
  js/src/orange-navbar.js
  js/src/popover.js
  js/src/quantity-selector.js
  js/src/scrollspy.js
  js/src/tab.js
  js/src/toast.js
  js/src/tooltip.js
  js/src/util/backdrop.js
  js/src/util/component-functions.js
  js/src/util/config.js
  js/src/util/focustrap.js
  js/src/util/index.js
  js/src/util/sanitizer.js
  js/src/util/scrollbar.js
  js/src/util/swipe.js
  js/src/util/template-factory.js
  package-lock.json
  package.json
  site/content/docs/versions.md
  site/data/docs-versions.yml
Labels: v5, chore, merge

#1714 feat(range): provide an example to display the value
  site/content/docs/5.3/forms/range.md
  site/content/docs/5.3/migration.md
Labels: v5, brand, component, docs, passed a11y review

#1921 Chore merge from 99867eb to f8a56da
  .cspell.json
  build/vnu-jar.js
  site/assets/scss/_content.scss
  site/content/docs/5.3/examples/_index.md
  site/content/docs/5.3/getting-started/javascript.md
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
  site/data/examples.yml
  site/layouts/shortcodes/scss-docs.html
Labels: v5, chore, merge

#1923 Docs: remove Orange logo from README
  README.md
Labels: v5, docs

#1803 Update tooltips and popover design according to UI Kit v5
  .bundlewatch.config.json
  js/src/popover.js
  js/src/tooltip.js
  scss/_popover.scss
  scss/_tooltip.scss
  scss/_variables.scss
  site/content/docs/5.3/migration.md
Labels: v5, brand, component, docs, passed design review

#1926 fix(docs): use `current_version` data in Getting Started > Download
  site/content/docs/5.3/getting-started/download.md
Labels: v5, docs, fix

#1927 Chore merge from aa50e23 to 92f9dda
  .github/workflows/node-sass.yml
  README.md
  config.yml
  js/src/tooltip.js
  js/src/util/sanitizer.js
  package-lock.json
  package.json
  scss/_button-group.scss
  scss/_buttons.scss
  scss/_pagination.scss
  scss/_tables.scss
  scss/_tooltip.scss
  scss/_utilities.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/forms/_form-range.scss
  scss/forms/_input-group.scss
  scss/orange-helvetica.scss
  scss/tests/mixins/_media-query-color-mode-full.test.scss
  site/assets/js/code-examples.js
  site/assets/js/snippets.js
  site/content/docs/5.3/components/alerts.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/popovers.md
  site/content/docs/5.3/components/toasts.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/getting-started/javascript.md
  site/content/docs/5.3/getting-started/webpack.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/display.md
  site/layouts/partials/js-data-attributes.md
  site/layouts/shortcodes/js-docs.html
Labels: v5, chore, merge
