Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2023-12, with the labels that each got.

#2388 Dark mode: remove `$accessible-orange`
  scss/_maps.scss
  scss/_variables.scss
  scss/forms/_form-check.scss
  site/assets/scss/_colors.scss
  site/content/docs/5.3/utilities/colors.md
Labels: v5, docs, css, color mode

#2396 Solaris icons: Change the access url.
  hugo.yml
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/footer.html
Labels: v5, docs, fix, communication

#2400 fix: change Solaris icons URLs in previous versions
  docs/5.0/examples/cheatsheet/cheatsheet.css
  docs/5.0/examples/cheatsheet/cheatsheet.rtl.css
  docs/5.0/extend/icons/index.html
  docs/5.1/examples/cheatsheet/cheatsheet.css
  docs/5.1/examples/cheatsheet/cheatsheet.rtl.css
  docs/5.1/extend/icons/index.html
  docs/5.2/extend/icons/index.html
  docs/5.3/extend/icons/index.html
Labels: docs, fix

#2402 chore(deps-dev): bump Storybook from 7.6.3 to 7.6.4
  package-lock.json
  package.json
Labels: v5, dependencies

#2382 Dark mode: Color handling in the colors
  scss/_breadcrumb.scss
  scss/_button-group.scss
  scss/_buttons.scss
  scss/_color-palette.scss
  scss/_maps.scss
  scss/_reboot.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/forms/_form-check.scss
  scss/forms/_form-select.scss
  site/assets/js/color.js
  site/assets/scss/_boosted.scss
  site/assets/scss/_colors.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_content.scss
  site/assets/scss/_masthead.scss
  site/assets/scss/_navbar.scss
  site/assets/scss/_search.scss
  site/assets/scss/_tarteaucitron.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.3/components/alerts.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/customize/color-modes.md
  site/content/docs/5.3/customize/color-palette.md
  site/content/docs/5.3/customize/color-theme.md
  site/content/docs/5.3/customize/color.md
  site/content/docs/5.3/customize/overview.md
  site/content/docs/5.3/customize/sass.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/examples/download-app/download-app.css
  site/content/docs/5.3/examples/download-app/index.html
  site/content/docs/5.3/examples/grid/grid.css
  site/content/docs/5.3/getting-started/accessibility.md
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/utilities/background.md
  site/content/docs/5.3/utilities/colors.md
  site/data/colors.yml
  site/data/palette.yml
  site/data/sidebar.yml
  site/data/theme-colors.yml
  site/layouts/shortcodes/card.html
  site/layouts/shortcodes/example.html
  site/layouts/shortcodes/js-docs.html
  site/layouts/shortcodes/placeholder.html
  site/layouts/shortcodes/scss-docs.html
Labels: color mode

#2408 Dark mode: fix black card in masonry example
  site/content/docs/5.3/examples/masonry/index.html
Labels: color mode

#2410 Dark mode: Spinners doc fix
  site/content/docs/5.3/components/spinners.md
Labels: color mode

#2413 Dark mode: enhance Color Modes v5.3.0 explanation in migration guide
  site/content/docs/5.3/migration.md
Labels: color mode

#2405 Dark mode: Pagination fix
  scss/_variables.scss
Labels: fix, color mode

#2415 fix(examples): drop underline of hovered footer links in Download page example
  site/content/docs/5.3/examples/download-app/download-app.css
Labels: v5, examples, fix

#2404 Dark mode: select fix
  scss/_variables.scss
Labels: fix, color mode

#2420 chore(deps-dev): bump Storybook from 7.6.4 to 7.6.5
  package-lock.json
  package.json
Labels: v5, dependencies

#2423 Dark mode: toggle theme
  site/layouts/partials/docs-navbar.html
Labels: color mode

#2421 Chore merge main from 4352422 to 958b610
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/pa11y.yml
  .github/workflows/percy.yml
  package-lock.json
  package.json
  site/content/docs/5.3/components/card.md
  site/content/docs/5.3/customize/sass.md
Labels: v5, chore, merge

#2424 Dark mode: Deprecate variables and CSS classes
  scss/_accordion.scss
  scss/_carousel.scss
  scss/_dropdown.scss
  scss/_navbar.scss
  scss/_variables.scss
  scss/forms/_form-select.scss
  site/assets/scss/_navbar.scss
  site/assets/scss/_syntax.scss
Labels: color mode

#2417 Dark mode: Dropdown fix design
  scss/_dropdown.scss
  scss/_variables.scss
Labels: fix, passed design review, color mode

#2406 Dark mode: Local nav and nav underline fix
  scss/_local-navigation.scss
  scss/_nav.scss
  scss/_root.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  site/content/docs/5.3/components/local-navigation.md
  site/content/docs/5.3/dark-mode.md
Labels: fix, passed design review, color mode

#2418 Dark mode: Table fix
  scss/_root.scss
  scss/_tables.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/mixins/_table-variants.scss
  site/content/docs/5.3/content/tables.md
Labels: fix, passed design review, color mode

#2380 Dark mode: Toasts
  site/content/docs/5.3/components/toasts.md
  site/content/docs/5.3/dark-mode.md
Labels: color mode

#2412 Dark mode: Navbar Color Schemes
  site/content/docs/5.3/components/navbar.md
Labels: color mode

#2431 chore(deps-dev): bump Storybook from 7.6.5 to 7.6.6
  package-lock.json
  package.json
Labels: v5, dependencies

#2428 Supra bar: fix mobile spacing
  scss/_orange-navbar.scss
Labels: v5, fix, css

#2437 Chore merge from 240b78e to e47f3fe
  package-lock.json
  package.json
  scss/tests/mixins/_utilities.test.scss
  site/layouts/_default/examples.html
  site/layouts/partials/docs-navbar.html
Labels: v5, chore, merge

#2439 fix(examples): remove unused `.bd-content` from Form example
  site/content/docs/5.3/examples/form/index.html
Labels: v5, examples, fix

#2432 Navbar: Handle in a proper way our dropdowns inside documentation navbar
  site/assets/scss/_navbar.scss
  site/assets/scss/_search.scss
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/docs-versions.html
Labels: v5, docs, fix, css

#2425 Dark mode: Theme switcher control
  .bundlewatch.config.json
  scss/_navbar.scss
  site/assets/scss/_navbar.scss
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/customize/color-modes.md
  site/layouts/_default/examples.html
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/icons.html
  site/layouts/shortcodes/orange-global-headers.html
Labels: color mode

#2427 Dark mode: drop bottom-right theme selector for Download page and Form examples
  site/content/docs/5.3/examples/download-app/index.html
  site/content/docs/5.3/examples/form/index.html
  site/layouts/_default/examples.html
  site/static/docs/5.3/assets/img/examples/download-app.png
  site/static/docs/5.3/assets/img/examples/download-app@2x.png
  site/static/docs/5.3/assets/img/examples/form.png
  site/static/docs/5.3/assets/img/examples/form@2x.png
Labels: color mode

#2436 Dark mode: add new navbar mode selector example
  site/content/docs/5.3/examples/navbar-mode-selector/index.html
  site/data/examples.yml
  site/static/docs/5.3/assets/img/examples/navbar-mode-selector.png
  site/static/docs/5.3/assets/img/examples/navbar-mode-selector@2x.png
Labels: examples, color mode
