Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2023-11, with the labels that each got.

#2351 Chore: merge from d769ae0 to a4d2f59
  package-lock.json
  package.json
  site/content/docs/5.3/components/offcanvas.md
  site/content/docs/5.3/examples/download-app/download-app.css
  site/static/docs/5.3/assets/js/color-modes.js
Labels: v5, chore, merge

#2353 fix(tooltips): two CSS vars had a double prefix
  scss/_tooltip.scss
Labels: v5, fix, css

#2352 Dark mode: Tooltips
  site/content/docs/5.3/dark-mode.md
Labels: color mode

#2099 Fix quantity selector focus state
  js/src/quantity-selector.js
  js/tests/unit/quantity-selector.spec.js
  scss/_variables.scss
  scss/forms/_quantity-selector.scss
  scss/mixins/_forms.scss
  site/content/docs/5.3/forms/quantity-selector.md
  site/content/docs/5.3/forms/validation.md
  site/content/docs/5.3/migration.md
Labels: v5, accessibility, css, passed a11y review, passed design review

#2354 fix(examples): apply correctly `.header-minimized` to the Navbars example
  site/content/docs/5.3/examples/navbars/index.html
  site/layouts/shortcodes/orange-global-headers.html
Labels: v5, examples, fix

#2345 Dark mode: Navbar & Orange navbar
  js/tests/visual/scrollspy.html
  scss/_navbar.scss
  scss/_variables.scss
  site/assets/scss/_subnav.scss
  site/content/docs/5.3/components/navbar.md
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/examples/download-app/index.html
  site/content/docs/5.3/examples/form/index.html
  site/content/docs/5.3/examples/navbar-sticky/index.html
  site/content/docs/5.3/examples/navbars/index.html
  site/layouts/partials/docs-navbar.html
  site/layouts/shortcodes/orange-global-headers.html
  site/layouts/shortcodes/orange-supra.html
Labels: color mode

#2349 Dark mode: Tables
  scss/_root.scss
  scss/_variables.scss
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/dark-mode.md
Labels: color mode

#2355 Dark mode: basic elements
  scss/_reboot.scss
  scss/_root.scss
  scss/_variables.scss
  site/content/docs/5.3/dark-mode.md
Labels: color mode

#2363 fix(typography): modify `.lead` values to match the DSM body text
  scss/_type.scss
  scss/_variables.scss
  site/content/docs/5.3/migration.md
Labels: v5, fix, css

#2366 Docs: Adding a link on the homepage
  site/layouts/partials/home/masthead.html
Labels: v5, docs

#2323 Dark mode: Dropdown variant
  js/tests/visual/dropdown.html
  scss/_button-group.scss
  scss/_buttons.scss
  scss/_dropdown.scss
  site/assets/scss/_content.scss
  site/content/docs/5.3/components/button-group.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/offcanvas.md
  site/content/docs/5.3/customize/color-modes.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/forms/input-group.md
Labels: color mode

#2369 Add color mode on Masonry example
  scss/_variables.scss
  site/content/docs/5.3/examples/masonry/index.html
Labels: color mode

#2368 Dark mode: Grid example
  site/content/docs/5.3/examples/grid/grid.css
  site/content/docs/5.3/examples/grid/index.html
Labels: color mode

#2374 Docs: Homepage tweaks
  site/assets/scss/_content.scss
  site/layouts/partials/home/components-utilities.html
Labels: v5, docs

#2375 Dark mode: Make docs callouts more highlighted
  site/assets/scss/_callouts.scss
Labels: color mode

#2381 Dark mode: Render the color theme switcher well
  site/layouts/_default/examples.html
Labels: color mode

#2377 Remove useless CSS since dropdown have been changed
  site/assets/scss/_navbar.scss
  site/layouts/_default/single.html
  site/layouts/partials/home/masthead.html
Labels: color mode

#2378 Dark mode: Proposals to handle dark mode code highlights
  site/assets/scss/_component-examples.scss
  site/assets/scss/_variables.scss
  site/layouts/shortcodes/example.html
  site/layouts/shortcodes/js-docs.html
  site/layouts/shortcodes/scss-docs.html
Labels: color mode

#2367 Dark mode: Download app example
  site/content/docs/5.3/examples/download-app/download-app.css
  site/content/docs/5.3/examples/download-app/index.html
Labels: color mode

#2371 Dark mode: handle orange in the doc
  site/assets/scss/_component-examples.scss
  site/assets/scss/_toc.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.3/utilities/spacing.md
  site/layouts/partials/home/get-started.html
Labels: color mode

#2370 Dark mode: Change functionnal colors in dark mode
  scss/_badge.scss
  scss/_buttons.scss
  scss/_variables-dark.scss
  scss/helpers/_color-bg.scss
  site/content/docs/5.3/components/badge.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/dark-mode.md
  site/layouts/shortcodes/orange-global-headers.html
  site/layouts/shortcodes/orange-supra.html
Labels: color mode

#2385 Chore merge main from 8a965ca
  .github/workflows/calibreapp-image-actions.yml
  js/src/util/sanitizer.js
  package-lock.json
  package.json
  scss/_accordion.scss
  scss/_modal.scss
  scss/_offcanvas.scss
  scss/_variables.scss
  scss/mixins/_grid.scss
  scss/tests/mixins/_auto-import-of-variables-dark.test.scss
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/customize/sass.md
  site/content/docs/5.3/getting-started/vite.md
Labels: v5, chore, merge

#2379 Docs: Micro anim on docs guidelines page
  site/assets/scss/_boosted.scss
Labels: v5, docs, enhancement, passed design review

#2387 Dark mode: add badge in /dark-mode page
  site/content/docs/5.3/dark-mode.md
Labels: docs, color mode

#2392 chore(deps-dev): bump Storybook from 7.5.3 to 7.6.0
  package-lock.json
  package.json
Labels: v5, dependencies, chore

#2394 chore(deps-dev): bump Storybook from 7.6.0 to 7.6.1
  package-lock.json
  package.json
Labels: v5, dependencies, chore
