Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2023-02, with the labels that each got.

#1814 chore(deps-dev): bump Storybook from 6.5.15 to 6.5.16
  package-lock.json
  package.json
Labels: dependencies, chore

#1775 Merge from Bootstrap started the 12th of Jan
  scss/_maps.scss
  scss/_progress.scss
  scss/mixins/_utilities.scss
  site/content/docs/5.2/components/progress.md
  site/content/docs/5.2/customize/color-modes.md
  site/content/docs/5.2/migration.md
  site/content/docs/5.2/utilities/colors.md
  site/content/docs/5.2/utilities/position.md
Labels: v5, merge

#1784 Fix syntax of migration guide after dark mode merge
  site/content/docs/5.2/migration.md
Labels: v5, docs, fix

#1815 chore(deps-dev): bump tarteaucitronjs from 1.9.9 to 1.10.0
  package-lock.json
  package.json
Labels: dependencies, chore

#1796 CSS: Fix `.form-switch`
  scss/_variables.scss
Labels: v5, brand, css, enhancement

#1793 Docs: Dropdown fixes
  scss/_button-group.scss
  scss/_nav.scss
  site/content/docs/5.2/components/dropdowns.md
Labels: v5, docs, fix, css, enhancement

#1824 fix(docs): use the right heading format for progress bars section in the migration guide
  site/content/docs/5.2/migration.md
Labels: v5, docs

#1817 Merge main 4162c5
  .eslintrc.json
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/cspell.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  README.md
  build/build-plugins.js
  build/change-version.js
  build/generate-sri.js
  build/vnu-jar.js
  package-lock.json
  package.json
  scss/_root.scss
  scss/_variables.scss
  scss/forms/_form-check.scss
  scss/mixins/_banner.scss
  scss/mixins/_color-mode.scss
  site/assets/js/code-examples.js
  site/assets/js/snippets.js
  site/assets/scss/_anchor.scss
  site/assets/scss/_clipboard-js.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_search.scss
  site/assets/scss/_syntax.scss
  site/assets/scss/_tarteaucitron.scss
  site/assets/scss/_variables.scss
  site/assets/scss/docs.scss
  site/content/docs/5.2/about/license.md
  site/content/docs/5.2/about/overview.md
  site/content/docs/5.2/components/carousel.md
  site/content/docs/5.2/customize/color-modes.md
  site/content/docs/5.2/getting-started/javascript.md
  site/content/docs/5.2/migration.md
  site/layouts/partials/docs-subnav.html
  site/layouts/partials/header.html
  site/static/docs/5.2/assets/js/color-modes.js
Labels: chore, merge

#1828 Chore merge 9th of February
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/css.yml
  .stylelintrc
  package-lock.json
  package.json
  scss/_functions.scss
  scss/_root.scss
  scss/_variables.scss
  scss/mixins/_utilities.scss
  scss/tests/jasmine.js
  scss/tests/mixins/_color-modes.test.scss
  scss/tests/mixins/_utilities.test.scss
  scss/tests/sass-true/register.js
  scss/tests/sass-true/runner.js
  scss/tests/utilities/_api.test.scss
  site/assets/scss/_masthead.scss
  site/assets/scss/_search.scss
  site/assets/scss/_variables.scss
  site/content/docs/5.3/components/navbar.md
  site/content/docs/5.3/examples/_index.md
  site/content/docs/5.3/forms/input-group.md
  site/content/docs/5.3/forms/overview.md
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/flex.md
  site/layouts/partials/social.html
Labels: chore, merge

#1829 Chore merge 13th of Feb
  .bundlewatch.config.json
  scss/_nav.scss
  scss/_variables.scss
  site/content/docs/5.3/components/navs-tabs.md
  site/content/docs/5.3/migration.md
Labels: v5, merge

#1841 fix(docs): let README in 5.2.3
  README.md
Labels: v5, docs, fix

#1794 Update color picker according to UI Kit v5
  .bundlewatch.config.json
  scss/_variables.scss
  scss/forms/_form-control.scss
  site/content/docs/5.3/forms/form-control.md
  site/content/docs/5.3/migration.md
Labels: v5, brand, component, docs, OK accessibility, OK design

#1827 Card: Add a shortcode to better generate example page
  site/content/docs/5.3/examples/cards-rtl/index.html
  site/content/docs/5.3/examples/cards/index.html
  site/layouts/shortcodes/card.html
Labels: v5, examples, enhancement

#1838 chore(merge main): patched commit → 9e17b2b
  .bundlewatch.config.json
  scss/_helpers.scss
  scss/_nav.scss
  scss/_reboot.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables.scss
  scss/helpers/_focus-ring.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.3/customize/css-variables.md
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/migration.md
  site/data/sidebar.yml
Labels: v5, merge

#1842 Chore merge from 4b12084
  LICENSE
  NOTICE.txt
  README.md
  build/build-plugins.js
  build/change-version.js
  build/generate-sri.js
  build/vnu-jar.js
  build/zip-examples.js
  nuget/boosted.nuspec
  nuget/boosted.sass.nuspec
  scss/_card.scss
  scss/_close.scss
  scss/_nav.scss
  scss/mixins/_banner.scss
  site/assets/js/application.js
  site/assets/js/code-examples.js
  site/assets/js/snippets.js
  site/assets/scss/_callouts.scss
  site/assets/scss/_clipboard-js.scss
  site/assets/scss/_component-examples.scss
  site/assets/scss/_syntax.scss
  site/assets/scss/_variables.scss
  site/assets/scss/docs.scss
  site/content/docs/5.3/components/accordion.md
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/close-button.md
  site/content/docs/5.3/components/toasts.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/reboot.md
  site/content/docs/5.3/examples/form/index.html
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/migration.md
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/footer.html
  site/layouts/shortcodes/orange-footer.html
  site/static/docs/5.3/assets/js/color-modes.js
Labels: v5, merge

#1843 Chore merge from da1c968
  package-lock.json
  package.json
  scss/_root.scss
  scss/_variables-dark.scss
  scss/vendor/_rfs.scss
  site/assets/scss/_content.scss
  site/content/docs/5.3/components/breadcrumb.md
  site/content/docs/5.3/components/button-group.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/popovers.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/reboot.md
  site/content/docs/5.3/customize/optimize.md
  site/content/docs/5.3/forms/overview.md
  site/content/docs/5.3/getting-started/rtl.md
  site/content/docs/5.3/getting-started/webpack.md
  site/layouts/partials/callouts/danger-async-methods.md
  site/layouts/partials/callouts/warning-color-assistive-technologies.md
  site/layouts/partials/callouts/warning-input-support.md
Labels: v5, merge

#1857 Shortcode: Adding the picture icon on placeholder when text to display is `"false"`
  site/content/docs/5.3/components/placeholders.md
  site/layouts/shortcodes/placeholder.html
Labels: v5, docs, enhancement

#1855 Chore merge from 846d660 to 4536f60
  .bundlewatch.config.json
  config.yml
  package-lock.json
  package.json
  scss/_buttons.scss
  scss/_grid.scss
  scss/_maps.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/boosted-grid.scss
  scss/helpers/_colored-links.scss
  scss/helpers/_icon-link.scss
  scss/mixins/_list-group.scss
  scss/mixins/_visually-hidden.scss
  scss/tests/utilities/_api.test.scss
  site/assets/scss/_clipboard-js.scss
  site/assets/scss/_component-examples.scss
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/customize/color-modes.md
  site/content/docs/5.3/customize/color.md
  site/content/docs/5.3/examples/_index.md
  site/content/docs/5.3/helpers/colored-links.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/link.md
  site/content/docs/5.3/utilities/z-index.md
  site/data/examples.yml
  site/layouts/_default/docs.html
  site/layouts/_default/examples.html
  site/layouts/partials/callouts/info-npm-starter.md
  site/layouts/shortcodes/example.html
  site/static/docs/5.3/assets/js/color-modes.js
Labels: v5, merge
