Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2024-09, with the labels that each got.

#2714 chore(merge main): patched commit → e3e00b5
  package-lock.json
  package.json
Labels: v5, chore, merge

#2715 chore(merge main): patched Boosted commit → e42878f
  package-lock.json
  package.json
Labels: chore

#2718 Docs: Fix typo in Scss file
  scss/_variables.scss
Labels: v5, css, enhancement

#2720 chore(merge main): patched commit → 329acbd
  package-lock.json
  package.json
  site/content/docs/5.3/about/overview.md
Labels: v5, chore, merge

#2721 [OUDS] chore(merge main): patched Boosted commit → d1d1f89
  hugo.yml
  package-lock.json
  package.json
  scss/_variables.scss
Labels: chore

#2722 Fix a11y audit: All texts must be included in a semantic tag (design callouts)
  site/layouts/shortcodes/design-callout-alert.html
Labels: v5, accessibility

#2709 Fix audit a11y: Change wrong images labels
  site/content/docs/5.3/about/brand.md
Labels: v5, accessibility, docs

#2707 Missing role='img'
  site/content/docs/5.3/examples/download-app/index.html
Labels: v5, accessibility, docs

#2708 Use EN version of a11y guidelines to avoid a switch of language
  site/content/docs/5.3/accessibility-statement/_index.md
  site/content/docs/5.3/examples/download-app/download-app.js
  site/content/docs/5.3/examples/download-app/index.html
  site/content/docs/5.3/getting-started/accessibility.md
Labels: v5, accessibility, docs

#2697 Fix a11y audit 5-4: figcaption color in dark mode
  scss/_variables.scss
Labels: v5, accessibility, docs

#2719 [OUDS] Docs: add 'Helpers > Stretched link' page
  site/content/docs/0.0/helpers/stretched-link.md
  site/data/sidebar.yml
Labels: docs

#2729 chore(merge main): patched commit → dce1df
  package-lock.json
  package.json
  site/content/docs/5.3/customize/options.md
Labels: v5, chore, merge

#2734 chore(deps-dev): bump Storybook from 8.2.9 to 8.3.0
  .storybook/main.js
  package-lock.json
  package.json
Labels: v5, dependencies

#2735 chore(deps-dev): bump pa11y-ci-reporter-html from 6.0.2 to 7.0.0
  package-lock.json
  package.json
Labels: v5, dependencies

#2717 [OUDS] Docs: add 'Helpers > Ratio' page
  site/content/docs/0.0/helpers/ratio.md
  site/data/sidebar.yml
Labels: docs

#2726 Fix a11y audit: enlarge touch targets of right side menu "On this page"
  site/assets/scss/_toc.scss
Labels: v5, accessibility, fix

#2705 Fix a11y audit 1-1: Add a title to the contextual right side nav
  site/layouts/_default/docs.html
Labels: v5, accessibility, docs

#2702 Fix a11y audit 3-1: Make a list of elements
  site/content/docs/5.3/guidelines/_index.md
Labels: v5, accessibility, docs

#2687 [OUDS] feat: Add 'Borders' token, utilities and documentation
  .bundlewatch.config.json
  scss/_maps.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables.scss
  scss/tests/customize/_ouds-web-bootstrap.test.scss
  scss/tokens/_raw.scss
  scss/tokens/_semantic.scss
  site/content/docs/0.0/migration-from-boosted.md
  site/content/docs/0.0/migration.md
  site/content/docs/0.0/utilities/borders.md
  site/content/docs/0.0/utilities/opacity.md
  site/data/sidebar.yml
  site/layouts/shortcodes/bootstrap-compatibility.html
Labels: docs, css

#2738 [OUDS] chore(merge main): patched Boosted commit → 9518929
  .storybook/main.js
  package-lock.json
  package.json
  scss/_variables.scss
  site/assets/scss/_toc.scss
  site/content/docs/0.0/getting-started/accessibility.md
  site/layouts/_default/docs.html
  site/layouts/shortcodes/design-callout-alert.html
Labels: chore

#2740 [OUDS] feat: update border width semantic tokens with new references and values
  scss/_maps.scss
  scss/_variables.scss
  scss/tests/customize/_ouds-web-bootstrap.test.scss
  scss/tokens/_semantic.scss
  site/content/docs/0.0/migration-from-boosted.md
  site/content/docs/0.0/migration.md
  site/content/docs/0.0/utilities/borders.md
Labels: feature

#2745 chore(merge main): patched commit → a7a45b2
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/tooltips.md
Labels: v5, chore, merge
