Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2024-02, with the labels that each got.

#2468 Chore merge main from 518b4d2 to b75f637
  package-lock.json
  package.json
  site/layouts/shortcodes/example.html
Labels: v5, chore, merge

#2473 chore(deps-dev): bump Storybook from 7.6.12 to 7.6.13
  package-lock.json
  package.json
Labels: dependencies, chore

#2474 Chore merge main from 52cc934 to 4e35f64
  .eslintignore
  .eslintrc.json
  js/src/modal.js
  js/src/scrollspy.js
  js/src/tooltip.js
  js/src/util/backdrop.js
  js/tests/unit/carousel.spec.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/offcanvas.spec.js
  js/tests/unit/orange-navbar.spec.js
  js/tests/unit/quantity-selector.spec.js
  js/tests/unit/scrollspy.spec.js
  js/tests/unit/tab.spec.js
  js/tests/unit/toast.spec.js
  js/tests/unit/tooltip.spec.js
  package-lock.json
  package.json
  scss/_accordion.scss
  scss/_buttons.scss
Labels: v5, chore, merge

#2475 fix(docs): remove extra 'new version' messages in Orange navbar examples from the v5.2
  docs/5.2/components/navbar/index.html
  docs/5.2/components/orange-navbar/index.html
Labels: v5, docs, fix

#2482 Chore merge from d30385b to c396a2a
  js/src/dom/selector-engine.js
  js/tests/unit/dom/selector-engine.spec.js
  js/tests/unit/modal.spec.js
  package-lock.json
  package.json
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
Labels: v5, chore, merge

#2488 Docs: Use oran.ge links when they exist
  .github/PULL_REQUEST_TEMPLATE.md
  hugo.yml
  site/content/docs/5.3/guidelines/_index.md
  site/data/design-guidelines.yml
  site/layouts/_default/single.html
  site/layouts/partials/home/orange-design-system.html
Labels: v5, docs

#2075 Docs: enhance doc for Solaris icons
  NOTICE.txt
  hugo.yml
  site/assets/scss/_component-examples.scss
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/title-bars.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/extend/icons.md
  site/content/docs/5.3/forms/checks-radios.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/colors.md
  site/layouts/partials/header.html
  site/static/docs/5.3/assets/img/boosted-cross.svg
  site/static/docs/5.3/assets/img/boosted-sprite.svg
  site/static/docs/5.3/assets/img/boosted-warning.svg
Labels: v5, docs

#2217 docs: add Icons rendering section
  site/content/docs/5.3/extend/icons.md
Labels: v5, docs, enhancement

#2495 Merge chore main from fa9c12a to 99562ba
  package-lock.json
  package.json
Labels: v5, merge
