Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2024-10, with the labels that each got.

#2696 Fix a11y audit: alt attribute of images containing text must contain this text
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
Labels: v5, accessibility

#2698 Fix a11y audit 0-1: Boosted homepage title
  site/layouts/partials/header.html
Labels: v5, accessibility, docs

#2690 Fix a11y audit: alt attribute of decorative images must be empty
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
  site/content/docs/5.3/migration.md
  site/layouts/partials/home/orange-design-system.html
  site/layouts/shortcodes/orange-global-headers.html
  site/layouts/shortcodes/orange-supra.html
Labels: v5, accessibility, docs

#2703 Fix a11y audit 3-2: Update `aria-label` and `title`
  site/layouts/_default/single.html
Labels: v5, accessibility, docs

#2752 chore(merge main): patched commit → 2fab352
  package-lock.json
  package.json
  scss/_card.scss
  scss/_nav.scss
  scss/mixins/_grid.scss
  site/content/docs/5.3/customize/options.md
Labels: v5, chore, merge

#2727 Fix a11y audit: change `<aside>` to `<nav>`
  site/layouts/_default/docs.html
  site/layouts/partials/docs-sidebar.html
Labels: v5, accessibility, docs

#2723 Docs: fix different links having same accessible name
  site/content/docs/5.3/about/license.md
Labels: v5, accessibility

#2704 Remove unnecessary role="img"
  build/vnu-jar.mjs
  site/content/docs/5.3/about/brand.md
  site/content/docs/5.3/components/scrollspy.md
  site/content/docs/5.3/customize/color-palette.md
  site/content/docs/5.3/examples/download-app/index.html
Labels: v5, accessibility, docs

#2751 feat: introduce `$ouds-border-radius-9999` raw token and create a `px-to-rem` Sass function
  scss/_functions.scss
  scss/_ouds-maps.scss
  scss/_variables.scss
  scss/tokens/_raw.scss
  scss/tokens/_semantic.scss
  site/content/docs/0.0/migration-from-boosted.md
  site/content/docs/0.0/migration.md
Labels: feature

#2759 chore(merge main): patched commit → 88bb06b
  package-lock.json
  package.json
  site/assets/scss/_masthead.scss
  site/content/docs/5.3/about/translations.md
  site/content/docs/5.3/layout/columns.md
  site/content/docs/5.3/utilities/spacing.md
  site/layouts/partials/examples/main.html
  site/layouts/partials/home/components-utilities.html
  site/layouts/partials/home/css-variables.html
  site/layouts/partials/home/customize.html
  site/layouts/partials/home/get-started.html
  site/layouts/partials/home/orange-design-system.html
  site/layouts/partials/home/plugins.html
Labels: v5, chore, merge

#2760 fix(forms): avoid .is-required element to be alone on a new line
  scss/forms/_labels.scss
Labels: v5, fix

#2701 Missing overflow-visible on some icon button examples
  site/content/docs/5.3/components/badge.md
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/examples/form/index.html
  site/content/docs/5.3/migration.md
  site/layouts/shortcodes/orange-global-headers.html
  site/layouts/shortcodes/orange-supra.html
Labels: bug, v5

#2699 Fix a11y audit 0-6: focus order for the copy button on code example
  site/assets/js/partials/code-examples.js
  site/assets/scss/_component-examples.scss
  site/layouts/shortcodes/example.html
  site/layouts/shortcodes/js-docs.html
  site/layouts/shortcodes/scss-docs.html
Labels: v5, js, accessibility, docs

#2778 chore(merge main): patched Boosted commit → be8268e
  .github/workflows/pa11y.yml
  build/vnu-jar.mjs
  package-lock.json
  package.json
  scss/forms/_labels.scss
  site/assets/js/partials/code-examples.js
  site/assets/scss/_component-examples.scss
  site/content/docs/0.0/about/license.md
  site/layouts/_default/docs.html
  site/layouts/partials/docs-sidebar.html
  site/layouts/shortcodes/example.html
  site/layouts/shortcodes/js-docs.html
  site/layouts/shortcodes/scss-docs.html
Labels: chore
