Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2024-07, with the labels that each got.

#2594 Chore merge main from 008bc23 to 7c39249
  .eslintrc.json
  package-lock.json
  package.json
Labels: chore, merge

#2598 [OUDS] Change blob reference from `/blob/main` to `/blob/ouds/main`
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/issue-labeled.yml
  README.md
  build/banner.mjs
  js/src/orange-navbar.js
  js/src/quantity-selector.js
  scss/mixins/_banner.scss
  site/assets/js/color.js
  site/assets/js/partials/back-to-top.js
Labels: chore

#2593 [OUDS] Drop deprecated `.btn-close-white`
  scss/_close.scss
  scss/_variables.scss
  site/content/docs/0.1/migration-from-boosted.md
Labels: chore, docs, css

#2602 [OUDS] Change `site/static` 'boosted' images name to 'ouds-web'
  NOTICE.txt
  site/content/docs/0.1/components/badge.md
  site/content/docs/0.1/components/buttons.md
  site/content/docs/0.1/components/close-button.md
  site/content/docs/0.1/components/orange-navbar.md
  site/content/docs/0.1/components/tags.md
  site/content/docs/0.1/components/title-bars.md
  site/content/docs/0.1/components/tooltips.md
  site/content/docs/0.1/content/tables.md
  site/content/docs/0.1/dark-mode.md
  site/content/docs/0.1/examples/form/index.html
  site/content/docs/0.1/extend/icons.md
  site/content/docs/0.1/forms/checks-radios.md
  site/content/docs/0.1/getting-started/parcel.md
  site/content/docs/0.1/getting-started/vite.md
  site/content/docs/0.1/getting-started/webpack.md
  site/layouts/partials/header.html
  site/layouts/shortcodes/orange-footer.html
  site/layouts/shortcodes/orange-global-headers.html
  site/layouts/shortcodes/orange-supra.html
  site/static/docs/0.1/assets/img/guides/parcel-dev-server-ouds-web.png
  site/static/docs/0.1/assets/img/guides/vite-dev-server-ouds-web.png
  site/static/docs/0.1/assets/img/guides/webpack-dev-server-ouds-web.png
  site/static/docs/0.1/assets/img/ouds-web-sprite.svg
  site/static/docs/0.1/assets/img/ouds-web-warning.svg
Labels: chore, docs

#2603 [OUDS] Switch `main` branch references to `ouds/main` branch
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/bundlewatch.yml
  .github/workflows/cspell.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/pa11y.yml
  README.md
  nuget/ouds-web.sass.nuspec
  site/layouts/partials/footer.html
Labels: chore, docs, build

#2604 Docs(storybook): load a temp OUDS Web docs 0.1 CSS asset
  .storybook/preview-head.html
Labels: docs, css

#2607 [OUDS] Change npm package name from 'ouds-web' to '@ouds/web'
  README.md
  package-lock.json
  package.json
  site/content/docs/0.1/customize/sass.md
  site/content/docs/0.1/getting-started/download.md
  site/content/docs/0.1/getting-started/rtl.md
  site/layouts/partials/home/customize.html
  site/layouts/partials/home/get-started.html
  site/layouts/partials/home/masthead.html
Labels: chore, build

#2613 chore: drop IcoMoon images
  .cspell.json
  site/static/docs/5.3/assets/img/icomoon-download-font.png
  site/static/docs/5.3/assets/img/icomoon-generate-font.png
  site/static/docs/5.3/assets/img/icomoon-import-icons.png
  site/static/docs/5.3/assets/img/icomoon-manage-projects.png
  site/static/docs/5.3/assets/img/icomoon-new-project.png
  site/static/docs/5.3/assets/img/icomoon-preferences.png
  site/static/docs/5.3/assets/img/icomoon-select-icons.png
Labels: v5, chore

#2616 chore(deps-dev): bump Storybook from 8.1.11 to 8.2.2
  package-lock.json
  package.json
Labels: v5, dependencies

#2617 [OUDS] Docs(storybook): reintegrate Storybook run and build
  build/modify-site.mjs
  modify-site.sh
  package.json
  stories/create-stories-from-doc.js
Labels: docs, squash

#2618 [OUDS] Fix(js): rename JS global value from 'ouds-web' to 'oudsWeb'
  build/rollup.config.mjs
  dist/js/ouds-web.bundle.js
  dist/js/ouds-web.bundle.min.js
  dist/js/ouds-web.bundle.min.js.map
  dist/js/ouds-web.js
  dist/js/ouds-web.min.js
  dist/js/ouds-web.min.js.map
  js/tests/visual/modal.html
  js/tests/visual/popover.html
  js/tests/visual/toast.html
  js/tests/visual/tooltip.html
  site/assets/js/color.js
  site/assets/js/partials/code-examples.js
  site/assets/js/partials/snippets.js
  stories/create-stories-from-doc.js
Labels: js, docs, fix

#2548 Docs: Add `<details><summary>` to hide design callouts
  site/assets/scss/_content.scss
  site/content/docs/5.3/components/badge.md
  site/content/docs/5.3/components/breadcrumb.md
  site/content/docs/5.3/components/button-group.md
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/carousel.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/navs-tabs.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/components/scrollspy.md
  site/content/docs/5.3/components/spinners.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/reboot.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/customize/color-palette.md
  site/content/docs/5.3/forms/input-group.md
  site/content/docs/5.3/forms/layout.md
  site/content/docs/5.3/getting-started/introduction.md
  site/content/docs/5.3/helpers/colored-links.md
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/helpers/icon-link.md
  site/content/docs/5.3/utilities/background.md
  site/content/docs/5.3/utilities/borders.md
  site/content/docs/5.3/utilities/colors.md
  site/content/docs/5.3/utilities/link.md
Labels: v5, docs

#2620 Chore merge from e20cc0d to 7f8fed4
  package-lock.json
  package.json
  scss/_back-to-top.scss
  scss/_carousel.scss
  scss/_modal.scss
  scss/_navbar.scss
  scss/_reboot.scss
  scss/forms/_form-check.scss
  scss/forms/_quantity-selector.scss
Labels: chore, merge

#2624 chore(merge main): patched Boosted commit → 8d59932
  package-lock.json
  package.json
Labels: chore, merge

#2623 [OUDS] Docs: Add visually-hidden to side menu of the docs
  site/layouts/partials/docs-sidebar.html
Labels: accessibility, docs

#2621 fix(switch): Handle the invalid case for unchecked switch
  .bundlewatch.config.json
  scss/_root.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/mixins/_forms.scss
  site/content/docs/5.3/migration.md
Labels: v5, fix, css

#2626 [OUDS] Chore(merge main): patched Boosted commit → fdbb7d3
  .bundlewatch.config.json
  scss/_root.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/mixins/_forms.scss
Labels: chore, merge

#2628 [OUDS] chore(workflows): comment content of notify.yml
  .github/workflows/notify.yml
Labels: chore, github_actions

#2629 [OUDS] chore(workflows): comment delete notify.yml
  .github/workflows/notify.yml
Labels: chore, github_actions

#2630 fix(composer): drop 'replace' property
  composer.json
Labels: v4, build

#2631 [OUDS] Fix(README): composer command line
  README.md
Labels: docs, fix, build

#2625 Docs: Add and hide callout from the documentation
  site/assets/scss/_content.scss
  site/content/docs/5.3/components/badge.md
  site/content/docs/5.3/components/breadcrumb.md
  site/content/docs/5.3/components/button-group.md
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/components/card.md
  site/content/docs/5.3/components/carousel.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/footer.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/navbar.md
  site/content/docs/5.3/components/navs-tabs.md
  site/content/docs/5.3/components/orange-navbar.md
  site/content/docs/5.3/components/popovers.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/components/scrollspy.md
  site/content/docs/5.3/components/spinners.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/reboot.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/customize/color-palette.md
  site/content/docs/5.3/examples/download-app/index.html
  site/content/docs/5.3/extend/icons.md
  site/content/docs/5.3/forms/checks-radios.md
  site/content/docs/5.3/forms/form-control.md
  site/content/docs/5.3/forms/input-group.md
  site/content/docs/5.3/forms/layout.md
  site/content/docs/5.3/forms/select.md
  site/content/docs/5.3/forms/validation.md
  site/content/docs/5.3/getting-started/introduction.md
  site/content/docs/5.3/guidelines/_index.md
  site/content/docs/5.3/helpers/color-background.md
  site/content/docs/5.3/helpers/colored-links.md
  site/content/docs/5.3/helpers/focus-ring.md
  site/content/docs/5.3/helpers/icon-link.md
  site/content/docs/5.3/helpers/stacks.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/background.md
  site/content/docs/5.3/utilities/borders.md
  site/content/docs/5.3/utilities/colors.md
  site/content/docs/5.3/utilities/link.md
Labels: v5, docs, enhancement

#2632 Chore merge from 74891cb to 16cd80a4
  js/src/dropdown.js
  js/src/tooltip.js
  js/src/util/index.js
  js/src/util/template-factory.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/popover.spec.js
  js/tests/unit/tooltip.spec.js
  js/tests/unit/util/index.spec.js
Labels: chore, merge

#2634 fix(README): npm version badge
  README.md
Labels: docs, fix, no squash

#2635 [OUDS] feat(css): Drop `form-star-rating()` mixin
  scss/mixins/_deprecate.scss
  scss/mixins/_star-rating.scss
  site/content/docs/0.0/migration-from-boosted.md
Labels: feature, docs, css

#2636 [OUDS] Fix(docs): change CodePen bug reports template
  .github/CONTRIBUTING.md
Labels: docs, fix

#2637 [OUDS] Docs: add new files names in Boosted migration page
  site/content/docs/0.0/migration-from-boosted.md
Labels: docs, enhancement

#2639 [OUDS] CI/CD: Browserstack tests
  js/tests/karma.conf.js
Labels: tools

#2640 Chore merge from 79a3fed to e8385b0
  package-lock.json
  package.json
  site/content/docs/5.3/examples/download-app/img/Emphasis_dark.png
  site/content/docs/5.3/examples/download-app/img/Input_dark.png
  site/content/docs/5.3/examples/download-app/img/List.png
  site/static/docs/5.3/assets/brand/orange-social.png
  site/static/docs/5.3/assets/img/boosted-guidelines.png
  site/static/docs/5.3/assets/img/boosted-guidelines@2x.png
  site/static/docs/5.3/assets/img/examples/cards-rtl@2x.png
  site/static/docs/5.3/assets/img/examples/download-app.png
  site/static/docs/5.3/assets/img/examples/navbar-mode-selector@2x.png
  site/static/docs/5.3/assets/img/examples/navbar-sticky.png
  site/static/docs/5.3/assets/img/examples/navbars.png
  site/static/docs/5.3/assets/img/examples/navbars@2x.png
  site/static/docs/5.3/assets/img/examples/stickers@2x.png
  site/static/docs/5.3/assets/img/examples/tags@2x.png
  site/static/docs/5.3/assets/img/examples/title-bars.png
  site/static/docs/5.3/assets/img/examples/title-bars@2x.png
  site/static/docs/5.3/assets/img/favicons/favicon-16x16.png
  site/static/docs/5.3/assets/img/favicons/favicon-32x32.png
  site/static/docs/5.3/assets/img/favicons/mstile-310x310.png
  site/static/docs/5.3/assets/img/guides/vite-dev-server.png
  site/static/docs/5.3/assets/img/guides/webpack-dev-server.png
  site/static/docs/5.3/assets/img/title-bars-illustrations/illustration-1440.png
Labels: chore, merge

#2638 [OUDS] Css: drop deprecated Boosted variables and change deprecated comments
  js/src/scrollspy.js
  js/src/toast.js
  scss/_dropdown.scss
  scss/_navbar.scss
  scss/_root.scss
  scss/_utilities.scss
  scss/_variables.scss
  site/content/docs/0.0/migration-from-boosted.md
Labels: docs, css

#2644 feat(buttons): add X social button
  .bundlewatch.config.json
  scss/_variables.scss
  site/content/docs/5.3/components/buttons.md
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/migration.md
  site/layouts/shortcodes/orange-footer.html
Labels: feature

#2650 [OUDS] docs: add 'Extend > Approach' page
  site/content/docs/0.0/extend/approach.md
  site/data/sidebar.yml
Labels: docs

#2657 [OUDS] docs: remove 'Getting started > Best practices' page
  site/content/docs/0.0/getting-started/best-practices.md
Labels: docs
