Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2024-04, with the labels that each got.

#2531 Chore merge main from 2ba7dae to fb4629f
  site/content/docs/5.3/examples/_index.md
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
  site/layouts/_default/_markup/render-image.html
  site/layouts/_default/single.html
  site/layouts/partials/examples/main.html
  site/layouts/partials/home/orange-design-system.html
  site/layouts/partials/responsive-img.html
  site/static/docs/5.3/assets/img/boosted-guidelines.png
  site/static/docs/5.3/assets/img/boosted-guidelines@2x.png
Labels: v5, chore, merge

#2537 Chore merge main from ee3bf1b to f68a47c
  package-lock.json
  package.json
Labels: v5, chore, merge

#2538 Deps: Group dependabot PRs for Storybook
  .github/dependabot.yml
Labels: v5, dependencies, enhancement

#2539 chore(deps-dev): bump Node from 20.11.1 to 20.12.1
  .nvmrc
Labels: v5, dependencies, chore

#2540 Chore merge from 1a3c287 to 868705b
  .eslintrc.json
  package-lock.json
  package.json
Labels: v5, chore, merge

#2547 chore(merge main): patched commit → ad0cc68
  package-lock.json
  package.json
Labels: v5, chore, merge

#2550 chore(merge main): patched commit → d7b22b7
  package-lock.json
  package.json
Labels: v5, chore, merge

#2549 CSS: Change the base dark mode red color palette
  scss/_color-palette.scss
  site/content/docs/5.3/migration.md
Labels: v5, css
