Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2024-03, with the labels that each got.

#2499 Chore merge main from 712e722 to bf8f2d2
  package-lock.json
  package.json
  site/layouts/_default/single.html
  site/layouts/partials/home/masthead.html
Labels: v5, merge

#2502 Use constant to define play/pause css class names for caroussel
  .bundlewatch.config.json
  js/src/carousel.js
Labels: v5, js, enhancement

#2503 chore(deps): bump tarteaucitronjs from 1.16.1 to 1.17.0
  package-lock.json
  package.json
  site/assets/js/tac.js
Labels: v5, dependencies, chore

#2512 chore(deps-dev): bump Storybook from v7 to v8
  .gitignore
  .nvmrc
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  package-lock.json
  package.json
  stories/create-stories-from-doc.js
Labels: v5, dependencies

#2529 chore(merge main): patched commit → 24f749c
  .eslintrc.json
  .storybook/main.js
  hugo.yml
  package-lock.json
  package.json
  site/assets/js/application.js
  site/assets/js/color.js
  site/assets/js/partials/back-to-top.js
  site/assets/js/partials/code-examples.js
  site/assets/js/partials/sidebar.js
  site/assets/js/partials/snippets.js
  site/assets/js/search.js
  site/assets/js/snippets.js
  site/assets/js/stackblitz.js
  site/assets/js/tac.js
  site/assets/js/vendor/clipboard.min.js
  site/assets/scss/_search.scss
  site/content/docs/5.3/components/alerts.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/toasts.md
  site/content/docs/5.3/docsref.md
  site/layouts/partials/header.html
  site/layouts/partials/scripts.html
  site/layouts/partials/stylesheet.html
  stories/create-stories-from-doc.js
Labels: v5, chore, merge

#2530 chore(merge main): patched commit → 24cc552
  hugo.yml
  package-lock.json
  package.json
  site/assets/js/search.js
  site/assets/js/snippets.js
  site/assets/js/stackblitz.js
  site/assets/scss/_search.scss
  site/assets/scss/docs.scss
  site/assets/scss/search.scss
  site/content/404.md
  site/content/docs/5.3/_index.html
  site/content/docs/5.3/dark-mode.md
  site/content/docs/5.3/docsref.md
  site/content/docs/5.3/examples/download-app/index.html
  site/content/docs/5.3/examples/form/index.html
  site/content/docs/5.3/examples/navbar-sticky/index.html
  site/content/docs/_index.html
  site/content/docs/versions.md
  site/layouts/_default/docs.html
  site/layouts/_default/examples.html
  site/layouts/partials/docs-navbar.html
  site/layouts/partials/docs-sidebar.html
  site/layouts/partials/examples/icons.html
  site/layouts/partials/header.html
  site/layouts/partials/scripts.html
  site/layouts/partials/stylesheet.html
  site/layouts/partials/theme-toggler.html
  site/layouts/sitemap.xml
Labels: v5, chore, merge
