Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2025-04, with the labels that each got.

#2908 docs: Add getting started>download page
  site/content/docs/0.3/getting-started/download.md
  site/data/sidebar.yml
  site/layouts/partials/callouts/info-npm-starter.md
  site/layouts/partials/examples/main.html
  site/layouts/partials/header.html
  site/layouts/shortcodes/callout.html
Labels: 📖 documentation

#2941 chore(merge main):patched commit → eed621d
  .cspell.json
  .github/SUPPORT.md
  README.md
  hugo.yml
  js/tests/unit/popover.spec.js
  js/tests/visual/tooltip.html
  package-lock.json
  package.json
  scss/_list-group.scss
  scss/_modal.scss
  scss/_offcanvas.scss
  scss/_progress.scss
  scss/_reboot.scss
  scss/_variables.scss
  site/assets/scss/_masthead.scss
  site/content/docs/5.3/about/overview.md
  site/content/docs/5.3/components/navbar.md
  site/content/docs/5.3/components/progress.md
  site/content/docs/5.3/content/tables.md
  site/content/docs/5.3/customize/sass.md
  site/content/docs/5.3/examples/tags/index.html
  site/content/docs/5.3/getting-started/introduction.md
  site/content/docs/5.3/helpers/icon-link.md
  site/content/docs/5.3/migration.md
  site/content/docs/5.3/utilities/borders.md
  site/layouts/partials/home/get-started.html
  site/layouts/partials/social.html
  site/layouts/partials/table-content.html
Labels: v5, chore, merge

#2958 Form helper: fix overlapping with required star and form helper
  scss/forms/_form-check.scss
  scss/forms/_labels.scss
Labels: v5, fix, css

#2973 chore(merge main):patched commit → b1e16bd
  .browserslistrc
Labels: v5, chore, merge

#2501 Focus: Remove default `z-index`
  scss/_accordion.scss
  scss/_buttons.scss
  scss/_list-group.scss
  scss/_nav.scss
  scss/_pagination.scss
  scss/forms/_form-check.scss
  scss/forms/_star-rating.scss
  scss/mixins/_focus.scss
  site/content/docs/5.3/migration.md
Labels: v5, fix, css

#2981 chore(merge main): patched Boosted commit → c41606e
  .browserslistrc
  .github/workflows/pa11y.yml
  package-lock.json
  package.json
  scss/_accordion.scss
  scss/_buttons.scss
  scss/_list-group.scss
  scss/_nav.scss
  scss/_pagination.scss
  scss/forms/_labels.scss
  scss/forms/_star-rating.scss
  scss/mixins/_focus.scss
  site/content/docs/0.4/migration.md
Labels: chore

#2985 chore (merge main): patched commit → 99a0dc6
  .cspell.json
  .github/CONTRIBUTING.md
  README.md
  scss/_card.scss
  site/content/docs/5.3/components/card.md
  site/content/docs/5.3/components/offcanvas.md
  site/content/docs/5.3/components/placeholders.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/content/reboot.md
  site/content/docs/5.3/customize/sass.md
  site/content/docs/5.3/getting-started/download.md
  site/content/docs/5.3/getting-started/parcel.md
  site/content/docs/5.3/getting-started/vite.md
  site/content/docs/5.3/getting-started/webpack.md
  site/data/translations.yml
Labels: v5, chore, merge

#2979 fix(storybook): remove directory when needed
  stories/create-stories-from-doc.js
Labels: v5, chore, 🔨 tool
