Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2025-03, with the labels that each got.

#2878 chore(merge main):patched commit → 90acd33
  js/tests/helpers/fixture.js
  package-lock.json
  package.json
  site/assets/js/partials/code-examples.js
  site/content/docs/5.3/components/collapse.md
  site/content/docs/5.3/components/dropdowns.md
  site/content/docs/5.3/components/list-group.md
  site/content/docs/5.3/components/modal.md
  site/content/docs/5.3/components/navs-tabs.md
  site/content/docs/5.3/components/offcanvas.md
  site/content/docs/5.3/components/popovers.md
  site/content/docs/5.3/components/toasts.md
  site/content/docs/5.3/components/tooltips.md
  site/content/docs/5.3/forms/checks-radios.md
Labels: v5, chore, merge

#2880 chore: add Maxime as a team member
  site/data/core-team.yml
Labels: chore

#2879 chore(merge main): patched Boosted commit → 3a687e4
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/dependabot.yml
  .github/workflows/pa11y.yml
  package-lock.json
  package.json
  site/layouts/_default/docs.html
  site/layouts/partials/docs-sidebar.html
Labels: chore

#2899 [OUDS] Remove ouds-web folder for documentation output
  .github/PULL_REQUEST_TEMPLATE.md
  build/modify-site.mjs
  build/zip-examples.mjs
  package.json
  stories/create-stories-from-doc.js
Labels: 📖 documentation

#2874 feat(component): Add Checkbox component
  .github/workflows/node-sass.yml
  scss/_forms.scss
  scss/_root.scss
  scss/_variables-dark.scss
  scss/_variables.scss
  scss/forms/_control-item.scss
  scss/forms/_form-check.scss
  scss/mixins/_forms.scss
  site/assets/js/tac.js
  site/content/docs/0.3/forms/checkbox.md
  site/content/docs/0.3/forms/checks-radios.md
  site/content/docs/0.3/forms/overview.md
  site/content/docs/0.3/forms/validation.md
  site/content/docs/0.3/getting-started/introduction.md
  site/content/docs/0.3/migration-from-boosted.md
  site/content/docs/0.3/migration.md
  site/data/sidebar.yml
Labels: ⚛️ component, 📖 documentation
