Repository Orange-OpenSource/Orange-Boosted-Bootstrap, pull requests merged in 2025-06, with the labels that each got.

#3011 [OUDS] docs use right bg color in migration md
  site/content/docs/0.4/migration.md
Labels: 📖 documentation, fix

#3006 [OUDS] Docs: add divider design doc link
  site/content/docs/0.4/helpers/divider.md
Labels: 📖 documentation, 🧩 enhancement

#3010 [OUDS] add title attibutes, bootstrap html handling and a callout on Breadcrumb
  scss/_breadcrumb.scss
  site/content/docs/0.4/components/breadcrumb.md
Labels: ⚛️ component, 📖 documentation, 🧩 enhancement

#2929 feat(browserlist): Browserlist updated
  .browserslistrc
  js/tests/browsers.js
  site/content/docs/0.4/getting-started/browsers-devices.md
Labels: chore, 🧰 library, 🛠️ technical

#3026 chore(merge main): patched commit → `0f63de9`
  .eslintrc.json
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/pa11y.yml
  .github/workflows/percy.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  build/docs-prep.sh
  build/zip-examples.mjs
  js/src/tooltip.js
  js/src/util/sanitizer.js
  js/tests/unit/popover.spec.js
  package-lock.json
  package.json
  scss/mixins/_box-shadow.scss
  scss/tests/mixins/_box-shadow.test.scss
  site/src/assets/examples/masonry/index.astro
  site/src/content/docs/components/accordion.mdx
  site/src/content/docs/components/popovers.mdx
  site/src/content/docs/components/tooltips.mdx
  site/src/content/docs/forms/range.mdx
  site/src/content/docs/getting-started/download.mdx
  site/src/content/docs/getting-started/introduction.mdx
  site/src/content/docs/getting-started/javascript.mdx
  site/src/layouts/DocsLayout.astro
  site/src/libs/astro.ts
  site/src/scss/_toc.scss
  site/static/docs/[version]/assets/img/bootstrap-intellisense-autocomplete.png
Labels: v5, chore, merge

#2998 feat(component): Add badge component
  .bundlewatch.config.json
  scss/_badge.scss
  scss/_variables.scss
  site/data/sidebar.yml
  site/src/content/docs/components/badge.mdx
  site/src/content/docs/migrations/migration-from-boosted.mdx
  site/src/content/docs/migrations/migration.mdx
Labels: ⚛️ component, 📖 documentation, css
